microsoft/FASTER

cc/CMakeLists.txt
cc/benchmark-dir/benchmark.cc
cc/playground/sum_store-dir/concurrent_recovery_test.h
cc/playground/sum_store-dir/single_threaded_recovery_test.h
cc/playground/sum_store-dir/sum_store.cc
cc/src/core/checkpoint_state.h
cc/src/core/faster.h
cc/src/core/guid.h
cc/src/core/light_epoch.h
cc/src/core/state_transitions.h
cc/src/device/file_system_disk.h
cc/src/device/null_disk.h
cc/test/recovery_test.h

Also store checkpoints by GUID, not by version. Now follows C# behavior.

CC: Split checkpoint into index & hybrid-log (full combines both).

---

README.md

The features of FASTER have been organized in an ordered list which makes for better comprehension.

Organized the features of FASTER.

---

cs/playground/ClassCache/Program.cs
cs/playground/ManagedSample1/Program.cs
cs/playground/ManagedSample2/Program.cs
cs/playground/ManagedSample3/Program.cs
cs/playground/ManagedSample4/Program.cs
cs/playground/ManagedSampleCore/Program.cs
cs/playground/NestedTypesTest/Program.cs
cs/playground/SumStore/ConcurrentRecoveryTest.cs
cs/playground/SumStore/ConcurrentTest.cs
cs/playground/SumStore/SingleThreadedRecoveryTest.cs
cs/src/core/Allocator/PersistentMemoryMalloc.cs
cs/src/core/Codegen/FasterHashTableCompiler.cs
cs/src/core/Codegen/HashTableManager.cs
cs/src/core/Codegen/MixedBlitManagedFasterHashTableCompiler.cs
cs/src/core/Epochs/LightEpoch.cs
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/ManagedLayer/FASTERFactory.cs
cs/src/core/ManagedLayer/MixedManagedFAST.cs
cs/test/BasicFASTERTests.cs
cs/test/FullRecoveryTests.cs
cs/test/ObjectFASTERTests.cs
cs/test/ObjectRecoveryTest.cs
cs/test/TestTypes.cs

Cleaning up the C# API for creating FASTER instances. We now have two classes (LogSettings and CheckpointSettings) for providing configuration information when creating an instance of FASTER.

API cleanup

---

README.md

Add badge to display the current version of this project's nuget package.
https://shields.io/#/examples/version

Add badge to display the current version of the nuget package.

---

cs/src/core/Allocator/MallocFixedPageSize.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERBase.cs

Fixing some leaks due to objects not being disposed properly

Fixing some leaks in FASTER cleanup

---

cs/README.md
cs/src/core/Index/FASTER/Checkpoint.cs

The state machine for index checkpointing is as follows:
REST -> PREP_INDEX_CHECKPOINT -> INDEX_CHECKPOINT -> REST

Fixed index checkpointing state machine

---

cc/test/in_memory_test.cc

This test shows how to use a Key object that stores an arbitrarily sized
uint16_t array. The array is first heap-allocated then copied onto the
HybridLog once the record has been allocated. The original
heap-allocated array can then be safely freed.

cc: Add a test for a variable length key

---

cc/src/core/faster.h

Following #145 it seems we missed a case where an RMW on a "growing" value that has gone pending will not be using the correct `value_size()` method.

[c++] support growing values in InternalContinuePendingRmw

---

cs/playground/FasterLogSample/Program.cs
cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Index/Common/LogSettings.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FasterLog/FasterLog.cs

Adding truly non-blocking TryAppend functionality. See sample for how this is used.

Fasterlog TryAppend

---

cc/src/core/checkpoint_locks.h
cc/src/core/faster.h
cc/src/core/internal_contexts.h
cc/test/in_memory_test.cc

Closes #170.
This is based on #186 PR.

[C++] Add delete operation

---

docs/cs/README.md

The original FASTER Nuget is deprecated.

Change link to Microsoft.FASTER

---

docs/cs/FasterLog.md

Documentation related to  #255 (implemented in #298).
@badrishc

[C#] Add documentation of publish-subscribe with uncommitted entries

---

cs/FASTER.sln
cs/samples/AzureBackedStore/App.config
cs/samples/AzureBackedStore/AzureBackedStore.csproj
cs/samples/AzureBackedStore/Functions.cs
cs/samples/AzureBackedStore/Program.cs
cs/samples/AzureBackedStore/Properties/AssemblyInfo.cs
cs/samples/AzureBackedStore/Types.cs

* FasterKV talks to Azure storage backend directly
* Upserts data, takes a checkpoint, recovers, tests reads

[C#] FasterKV + Azure storage backend sample

---

cs/benchmark/FasterYcsbBenchmark.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/FASTERThread.cs

Fix https://github.com/microsoft/FASTER/issues/321

[C#] Fixing issue with frequent CPR during RMW workload

---

cs/src/devices/AzureStorageDevice/AzureStorageDevice.cs
cs/src/devices/AzureStorageDevice/BlobEntry.cs
cs/src/devices/AzureStorageDevice/DefaultBlobManager.cs
cs/src/devices/AzureStorageDevice/IBlobManager.cs

Thanks to @sebastianburckhardt for the contributions.

[C#] Azure Storage Device improvements

---

cs/src/core/Device/LocalStorageDevice.cs
cs/src/core/Utilities/Native32.cs

* Added config to disable process/volume privileges for `LocalStorageDevice` (`LocalStorageDevice.UsePrivileges`)
* Do not request process privilege if `preallocateFile` is set to false for device
Fix https://github.com/microsoft/FASTER/issues/379

[C#] Process and volume privilege for LocalStorageDevice

---

cs/src/core/Allocator/MallocFixedPageSize.cs
cs/src/core/Device/LocalStorageDevice.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/Recovery/IndexCheckpoint.cs
cs/src/core/Index/Recovery/IndexRecovery.cs
cs/src/core/Index/Synchronization/IndexSnapshotStateMachine.cs
cs/src/core/Utilities/AsyncResultTypes.cs
cs/src/core/Utilities/BufferPool.cs
cs/test/AsyncTests.cs
cs/test/BasicDiskFASTERTests.cs
cs/test/ObjectRecoveryTest2.cs
cs/test/ObjectRecoveryTest3.cs
cs/test/ObjectRecoveryTestTypes.cs
cs/test/ReadAddressTests.cs
cs/test/RecoverContinueTests.cs
cs/test/RecoveryChecks.cs
cs/test/RecoveryTestTypes.cs
cs/test/SimpleRecoveryTest.cs
cs/test/TestTypes.cs
cs/test/VLTestTypes.cs

Fix https://github.com/microsoft/FASTER/issues/324

[C#] Support index checkpointing with read cache enabled

---

cs/src/core/Index/Common/RecordInfo.cs
cs/test/LockTests.cs

Also remove no-longer-needed re-entrancy from RecordInfo.SpinLock()

Fix and re-enable RecordInfoLockTest

---

cs/src/core/Index/Common/Contexts.cs

Fix https://github.com/microsoft/FASTER/issues/411

[C#] Dispose input on pending context dispose.

---

cs/test/BasicDiskFASTERTests.cs
cs/test/DeviceFasterLogTests.cs

Added tests when using Leases. Tests: PageBlobFasterLogTestWithLease and PageBlobWriteReadWithLease tests

Added tests when using Leases with Azure Storage Blobs

---

docs/_docs/23-fasterkv-tuning.md

- Parameter name is ``ReadCacheSettings`` not ``ReadCache`
- removed extra instead

Slightly improve 23-fasterkv-tuning.md

---

cs/src/core/Index/Common/CompletedOutput.cs
cs/src/core/Index/FASTER/FASTERThread.cs
cs/test/CompletePendingTests.cs

Need to indicate status of the operation so the caller knows if the key was found

[C#] Add Status to CompletedOutput

---

cs/src/core/Index/FasterLog/FasterLog.cs

FasterLog.TryEnqueue / TryAppend do epoch.Resume before calling into AllocatorBase.TryAllocate, but do not do a catch + epoch.suspend around the call.

[C#] Pre-validate length before FasterLog allocation

---

cs/src/core/Index/FASTER/FASTERImpl.cs
cs/test/ReproReadCacheTest.cs

Fix https://github.com/microsoft/FASTER/issues/482

[C#] Fix read cache boundary condition bug

---

cc/src/core/light_epoch.h
cc/test/paging_test.h

Fix https://github.com/microsoft/FASTER/issues/481

[C++] Fix epoch scan range

---

README.md
docs/_data/navigation.yml
docs/_docs/85-dpr-basics.md
docs/_docs/97-dpr-detail.md

Some write-ups about how to use libDPR

Documentation for DPR

---

cs/remote/src/FASTER.client/MemoryParameterSerializer.cs
cs/remote/src/FASTER.server/SubscribeKVBroker.cs

Fixed small nit in MemoryparamSerializer to return Memory<byte> of correct length, and in publish call corner case

Bug fixes in pub-sub

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/AsyncIOContext.cs
cs/src/core/Async/ReadAsync.cs
cs/src/core/ClientSession/AdvancedClientSession.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/test/BasicFASTERTests.cs
cs/test/ReadAddressTests.cs
cs/test/TestUtils.cs
cs/test/WaitForCommit.cs

This allows specifying an address below which Read() will not look up a record (it will return Status.NOTFOUND)

Add ReadFlags.MinAddress

---

cc/src/core/compact.h
cc/src/core/faster.h
cc/src/core/internal_contexts.h

Improvements ported from ongoing hot-cold design implementation.

[C++] Single log lookup compaction improvements

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Index/CheckpointManagement/DeviceLogCommitCheckpointManager.cs
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/Interfaces/IFasterKV.cs
cs/src/core/Index/Recovery/DeltaLog.cs
cs/src/core/Index/Recovery/ICheckpointManager.cs
cs/src/core/Index/Recovery/LocalCheckpointManager.cs
cs/src/core/Index/Recovery/Recovery.cs
cs/src/core/Index/Synchronization/FasterStateMachine.cs
cs/src/core/Index/Synchronization/HybridLogCheckpointTask.cs
cs/test/CheckpointManagerTests.cs
cs/test/DeltaLogTests.cs
cs/test/RecoveryChecks.cs

- Add ability to recover to a specific version within an incremental snapshot
- Add ability to remove a particular checkpoint guid from ICheckpointManager instead of just PurgeAll()

[C#] Checkpoint & Versioning Utilities

---

cs/src/core/Allocator/GenericAllocator.cs

Fix https://github.com/microsoft/FASTER/issues/617

[C#] Fix object serialization boundary condition

---

cs/src/core/Device/LocalStorageDevice.cs
cs/src/core/Device/ManagedLocalStorageDevice.cs
cs/src/devices/AzureStorageDevice/AzureStorageDevice.cs

Fix https://github.com/microsoft/FASTER/issues/626

[C#] Delete file handles that may not be cached in memory

---

cs/src/core/Index/Recovery/Recovery.cs

Fix https://github.com/microsoft/FASTER/issues/640

[C#] Throw exception on page read/flush error during restore

---

cs/remote/samples/FixedLenClient/Functions.cs
cs/remote/samples/FixedLenClient/Program.cs
cs/remote/samples/VarLenClient/CustomTypeFunctions.cs
cs/remote/samples/VarLenClient/CustomTypeSamples.cs
cs/remote/samples/VarLenClient/MemoryFunctions.cs
cs/remote/samples/VarLenClient/MemorySamples.cs
cs/remote/src/FASTER.client/ClientSession.cs
cs/remote/src/FASTER.client/Status.cs
cs/remote/src/FASTER.client/StatusCode.cs
cs/remote/test/FASTER.remote.test/FixedLenClient.cs
cs/remote/test/FASTER.remote.test/VarLenMemoryClient.cs
cs/src/core/Utilities/Status.cs

[C#] Wire status into remote v2

---

cs/remote/src/FASTER.server/WebsocketServerSession.cs

This PR fixes a bug in which the publish call for websocket server was not adding the websocket header while sending the subscribed values.

[C#] bug-fix for publish in websockets

---

cs/src/core/Allocator/GenericAllocator.cs

Fix https://github.com/microsoft/FASTER/issues/672

[C#] Fix object log address retrieval ranges

---

cs/src/core/FasterLog/FasterLogIterator.cs

[C#] Fix Commit Record Offset Calculation

---

cs/src/core/Index/Common/RecordInfo.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/test/TestTypes.cs

Also correct a typo in kExclusiveLockBits name

[C#] Make sure XxxInfo.RecordInfo is set on IFunctions calls

---

cs/src/core/Epochs/LightEpoch.cs
cs/src/core/Index/Common/CompletedOutput.cs
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/Common/RecordInfo.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/FASTERThread.cs
cs/src/core/Utilities/BufferPool.cs
cs/src/core/Utilities/CompletionEvent.cs
cs/src/core/Utilities/LockTable.cs
cs/src/core/Utilities/LockUtility.cs
cs/src/core/VarLen/SpanByte.cs
cs/src/core/VarLen/SpanByteComparer.cs
cs/src/core/VarLen/SpanByteFunctions.cs
cs/test/ReadCacheChainTests.cs

These tests specifically target 'long' and SpanByte

[C#] Multithreading tests and fixes

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/ClientSession/ILockableContext.cs
cs/src/core/ClientSession/LockableContext.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/Interfaces/UpdateInfo.cs

Context that is lockable, plus has automatic epoch handling.

[C#] Add LockableContext API to client session

---

cs/test/StateMachineTests.cs

Fix Lockable Contexts scenarios for state machine tests

Fix State Machine Tests

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Async/AsyncOperationInternal.cs
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/test/NeedCopyUpdateTests.cs

HeadAddress may go above doingCU's logicalAddress if BlockAllocate resulted in BumpCurrentEpoch(OnPagesClosed) running

[C#]Add CreateNewRecordRMW check for HeadAddress after BlockAllocate

---

cs/src/core/FasterLog/FasterLogIterator.cs
cs/src/core/FasterLog/FasterLogRecoveryInfo.cs
cs/test/FasterLogTests.cs

iterator NPE fix

---

cs/src/core/FasterLog/FasterLog.cs

If we await CommitAsync, and the operation does not start a new commit, we currently return immediately. Instead, we need to make sure commit has completed until the tail as of the CommitAsync call. Commit(spinWait: true) already ensures this, but the check was missing in CommitAsync.

[C#] FasterLog CommitAsync wait if no new commit done

---

.gitignore
cs/FASTER.sln
cs/performance/BenchmarkDotNet/BenchmarkDotNetTests.csproj
cs/performance/BenchmarkDotNet/BenchmarkDotNetTestsApp.cs
cs/performance/BenchmarkDotNet/LightEpochTests.cs
cs/performance/BenchmarkDotNet/README.md
cs/performance/BenchmarkDotNet/SyncVsAsyncTests.cs
cs/playground/AsyncStress/IFasterWrapper.cs

Added a BenchmarkDotNet project with a couple simple initial tests

[C#] Add initial Benchmarkdotnet tests

---

cs/src/core/Index/FASTER/FASTERImpl.cs
cs/test/AdvancedLockTests.cs

Fixes intermittent failure of SameKeyInsertAndCTTTest

[C#] Fix test and CAS-failure handling in CopyToTail

---

cs/samples/MemOnlyCache/Program.cs
cs/samples/ReadAddress/VersionedReadApp.cs
cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Epochs/LightEpoch.cs
cs/src/core/Index/FASTER/Implementation/ContinuePending.cs
cs/src/core/Index/FASTER/Implementation/EphemeralLocking.cs
cs/src/core/Index/FASTER/Implementation/Helpers.cs
cs/src/core/Index/FASTER/Implementation/InternalDelete.cs
cs/src/core/Index/FASTER/Implementation/InternalLock.cs
cs/src/core/Index/FASTER/Implementation/InternalRMW.cs
cs/src/core/Index/FASTER/Implementation/InternalRead.cs
cs/src/core/Index/FASTER/Implementation/InternalUpsert.cs
cs/src/core/Index/FASTER/Implementation/ReadCache.cs
cs/src/core/Index/FASTER/Implementation/RecordSource.cs
cs/src/core/Utilities/LockUtility.cs

Fix ReadFromImmutable's CopyToTailFromReadOnly loop to catch when the source address has dropped below HeadAddress
Page closing logic is simplified, linearized
Fix https://github.com/microsoft/FASTER/issues/791

[C#] Fix NullRef in ReadFromImmutable

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/FASTER/Implementation/FindRecord.cs
cs/src/core/Index/Recovery/Recovery.cs
cs/src/core/Index/Synchronization/FasterStateMachine.cs
cs/src/core/Index/Synchronization/HybridLogCheckpointTask.cs

As it can block other threads.

[C#] Do not hold epochs during a large flush operation

---

cs/src/core/ClientSession/ClientSession.cs
cs/src/core/Index/Common/FasterKVSettings.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERThread.cs
cs/src/core/Index/FASTER/Implementation/ContainsKeyInMemory.cs
cs/src/core/Index/FASTER/Implementation/EpochOperations.cs
cs/src/core/Index/FASTER/Implementation/InternalDelete.cs
cs/src/core/Index/FASTER/Implementation/InternalRMW.cs
cs/src/core/Index/FASTER/Implementation/InternalRead.cs
cs/src/core/Index/FASTER/Implementation/InternalUpsert.cs
cs/src/core/Index/Synchronization/FasterStateMachine.cs
cs/src/core/Index/Synchronization/IndexResizeStateMachine.cs
cs/src/core/Index/Synchronization/VersionChangeStateMachine.cs
cs/test/StateMachineBarrierTests.cs
cs/test/ThreadSession.cs

* Make sure ongoing multi-key ops drain out in PREPARE
* Correctly handle index resize

[C#] State machine adjustments

---

cs/src/core/Async/ReadAsync.cs

Fix https://github.com/microsoft/FASTER/issues/820

[C#] Fix the NoKey setting in ReadAsync

---

cs/benchmark/ConcurrentDictionaryBenchmark.cs
cs/benchmark/FasterSpanByteYcsbBenchmark.cs
cs/benchmark/FasterYcsbBenchmark.cs
cs/benchmark/Options.cs
cs/benchmark/TestLoader.cs
cs/benchmark/YcsbConstants.cs

Also change "-r read%" commandline argument to "-rumd read%,upsert%,rmw%,delete%"

[C#] Add Delete to YCSB Benchmark

---

cs/src/core/FasterLog/FasterLog.cs

Add DoAutoRefresh when enqueueing record with fastCommitMode enabled.

fix autorefresh for fastCommitMode

---

cs/src/core/Allocator/GenericAllocator.cs

Fix flush with generic allocator so that we do not write invalid data to disk in rare cases (e.g. record was valid when making initial image, but was subsequently set invalid)

Fix flush corner case with generic allocator

---

cs/remote/samples/FixedLenServer/FixedLenServer.csproj
cs/remote/samples/VarLenServer/VarLenServer.csproj

Nuget package system.text.json ver 7.0 had a security vulnerability, so needed to update the samples to use ver 8.0.5

Updated system.text.json to ver 8.0.5 so it is compliant with security
