cc/src/core/light_epoch.h

The constant `kTableSize` is the same as `Thread::kMaxNumThreads`: https://github.com/Microsoft/FASTER/blob/9c9d3e4c86f8e83c505290cf9f0baed549d3943b/cc/src/core/light_epoch.h#L120
The constructor allows one to specify a `size` but defaults to `kTableSize`: https://github.com/Microsoft/FASTER/blob/9c9d3e4c86f8e83c505290cf9f0baed549d3943b/cc/src/core/light_epoch.h#L140-L146
In `Initialize`, we set the `table_` to an allocation based on the `size`: https://github.com/Microsoft/FASTER/blob/9c9d3e4c86f8e83c505290cf9f0baed549d3943b/cc/src/core/light_epoch.h#L153-L158
These methods loop over the `table_` based on `Thread::kMaxNumThreads` instead of the appropriate size: https://github.com/Microsoft/FASTER/blob/9c9d3e4c86f8e83c505290cf9f0baed549d3943b/cc/src/core/light_epoch.h#L296-L318

fix memory safety issue in LightEpoch class

---

cc/src/core/record.h
cc/src/core/recovery_status.h
cc/src/core/thread.h

Removed a redundant static_assert() and a check against a pointer (guard for delete). Updated a comment to match a constant value.

Minor Refactoring

---

cs/FASTER.sln
cs/playground/ManagedSampleCore/App.config
cs/playground/ManagedSampleCore/Functions.cs
cs/playground/ManagedSampleCore/ICustomFaster.cs
cs/playground/ManagedSampleCore/InputStruct.cs
cs/playground/ManagedSampleCore/KeyStruct.cs
cs/playground/ManagedSampleCore/ManagedSampleCore.csproj
cs/playground/ManagedSampleCore/OutputStruct.cs
cs/playground/ManagedSampleCore/Program.cs
cs/playground/ManagedSampleCore/Properties/AssemblyInfo.cs
cs/playground/ManagedSampleCore/ValueStruct.cs
cs/src/core/Codegen/CompilerBase.cs
cs/src/core/Epochs/LightEpoch.cs
cs/src/core/FASTER.core.csproj

if merged, published app with memory-only pattern on linux will be able to run.
this fix following problems.
* strange NetCoreAssemblyReferences list is built in linux(because of TRUSTED_PLATFORM_ASSEMBLIES's spec)
* exception occured when `dotnet run` because of differences of handling resource between core and netframework
* get `..\Index\FASTER\FASTERImpl.cs;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8` from ResourceManager.GetString in netcoreapp
* using EmbeddedResource instead
* exception occured when calling LightEpoch.ReserveEntryForThread in linux(using Thread.CurrentThread.ManagedThreadId instead)
* be careful to performance regression

fixes for "dotnet run" and run on linux

---

cc/test/recovery_test.h

Hi,
I fixed a little typo in recovery test.
(I think this typo was generated at when `wasted_space[3]` was added)

Fix a diagnostic message typo in recovery test

---

.travis.yml

Hi,
I feel that it is very convenient to use a CI service to ensure pull requests can be built.
Using Travis CI may be suitable for that purpose ([Microsoft/TypeScript repository uses Travis CI](https://travis-ci.org/Microsoft/TypeScript/pull_requests)).
I already tested that CI service by my forked FASTER repository. Please check below.
https://travis-ci.org/quiye/FASTER/builds/436895454

Used the CI service

---

cs/src/core/FASTER.core.csproj

Add missing dependency on `Microsoft.CodeAnalysis.Analyzers` package, to ensure correct version is restored.
A dependency on package `Microsoft.CodeAnalysis.Analyzers` v1.1.0 implicitly shows up for csharp projects in VS2017, but that package version will not be downloaded / restored on a new machine unless the dependency is called out explicitly in the .csproj file.

Add missing dependency on Microsoft.CodeAnalysis.Analyzers v1.1.0

---

cs/src/core/Allocator/PersistentMemoryMalloc.cs
cs/src/core/Device/ManagedLocalStorageDevice.cs
cs/src/core/Index/FASTER/AsyncIO.cs
cs/src/core/Index/FASTER/FASTERBase.cs
cs/src/core/ManagedLayer/FASTERFactory.cs
cs/src/core/Properties/Resources.Designer.cs

Fix some problems with garbled / missing API doc comments.
Example of compile-time warnings this change fixes:
```
Severity Code Description Project File Line Suppression State
Warning CS1570 XML comment has badly formed XML -- 'Expected an end tag for element 'summary'.' FASTER.core(net46), FASTER.core(netstandard2.0) E:\Depot\GitHub\MSR-FASTER\cs\src\core\Properties\Resources.Designer.cs 65 Active
Warning CS1570 XML comment has badly formed XML -- 'End tag was not expected at this location.' FASTER.core(net46), FASTER.core(netstandard2.0) E:\Depot\GitHub\MSR-FASTER\cs\src\core\Properties\Resources.Designer.cs 83 Active
Warning CS1572 XML comment has a param tag for 'untilAddress', but there is no parameter by that name FASTER.core(net46), FASTER.core(netstandard2.0) …
```

Fix some problems with garbled / missing API doc comments.

---

azure-pipelines.yml

Add a build definition file for Azure Pipeline build, to build and test the C# code in this repo.
https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net
Runs multiple jobs to build + test each platform/config combination.
- (x64 | AnyCPU) * (Debug | Release)
- Runs all test cases found in builds.
- maxParallel = 2
I tested this on a private VSTS account so I can confirm this build definition runs successfully on the standard `Hosted VS2017` build hosts.
Currently, the only CI build configured for this project is for the C++ code.
https://github.com/Microsoft/FASTER/blob/master/.travis.yml
https://travis-ci.org/Microsoft/FASTER
If you want to hook this up as a CI build and PR gate check (recommended), then there are a few additional manual steps required to set up a new Azure build …

Add azure-pipelines.yml file for Azure Pipeline build.

---

cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/FASTER/AsyncIO.cs
cs/src/core/Index/FASTER/Checkpoint.cs
cs/src/core/Index/FASTER/Recovery.cs
cs/src/core/Utilities/AsyncResultTypes.cs
cs/test/LargeObjectTests.cs
cs/test/ObjectTestTypes.cs

The C# version of FASTER consists of a separate object log that contains the C# objects that are heap-allocated. This checking writes and reads the object log for a page incrementally, in chunks of 100MB. This avoids collecting all the data in an in-memory buffer before reading or writing them. There is a limit of 2GB per key-value pair in this setting.

Incremental large obj

---

cs/benchmark/FasterYcsbBenchmark.cs
cs/playground/ManagedSample3/Program.cs
cs/playground/ManagedSample4/Program.cs
cs/playground/NestedTypesTest/Program.cs
cs/src/core/Allocator/PMMAsyncIO.cs
cs/src/core/Allocator/PersistentMemoryMalloc.cs
cs/src/core/Codegen/FasterHashTableCompiler.cs
cs/src/core/Codegen/HashTableManager.cs
cs/src/core/Index/FASTER/Checkpoint.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERBase.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/Recovery.cs
cs/src/core/ManagedLayer/FASTERFactory.cs
cs/src/core/Utilities/AsyncResultTypes.cs
cs/src/core/Utilities/PageAsyncResultTypes.cs
cs/test/LargeObjectTests.cs
cs/test/ObjectFASTERTests.cs
cs/test/SimpleRecoveryTest.cs

PersistentMemoryMalloc does not need to be codegen'ed any longer. This makes debugging significantly more tractable. Log page size is now set as a constant (32MB), because making it readonly (allowing user to provide it as a log setting) results in a 5% performance penalty. When PMM was codegen'ed, we were able to replace the constant in generated code - this is no longer possible. This checkin also marks a step in the direction of having a non-codegen version of FASTER.

Refactoring so that PMM does not need to be codegen'ed

---

cs/playground/ClassCache/Program.cs
cs/playground/ClassSample/Program.cs
cs/playground/MixedSample/Program.cs
cs/src/core/Device/Devices.cs
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/FASTER/Checkpoint.cs
cs/src/core/Index/FASTER/Recovery.cs
cs/test/BasicFASTERTests.cs
cs/test/LargeObjectTests.cs
cs/test/MiscFASTERTests.cs
cs/test/ObjectFASTERTests.cs
cs/test/ObjectRecoveryTest.cs

We have merged the object log and normal hybrid log devices into a single storage device abstraction. This means we no longer need a separate API for CreateObjectLogDevice. To create the normal and object log devices, you do the following:
```CSharp
var log =  Devices.CreateLogDevice(Path.GetTempPath() + "hlog.log");
var objlog = Devices.CreateLogDevice(Path.GetTempPath() + "hlog.obj.log");
```
To preallocate file segments, you may pass in the argument `preallocateFile = true` to `CreateLogDevice`.

Remove CreateObjectLogDevice API due to redundancy.

---

azure-pipelines.yml
cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/BlittableAllocator.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Utilities/PageAsyncResultTypes.cs
cs/test/BasicDiskFASTERTests.cs
cs/test/ObjectFASTERTests.cs
cs/test/RecoverContinueTests.cs

If we move the read-only marker by a small amount, we currently rewrite the entire page (including objects on the page), because it is currently optimized for page-aligned flushes only.
This PR fixes incremental flushes within the same page, so that we flush only the delta (at sector boundary).
Further, objects pointed to by entries in the log are now guaranteed to get serialized exactly once. When the marker moves from a location partially with a sector, we first read the existing sector from storage, update the new log entries, and write out the updated sector.

Partial flush with object log

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/BlittableAllocator.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Allocator/IFasterScanIterator.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/Interfaces/IFasterKV.cs
cs/src/core/Utilities/BufferPool.cs
cs/src/core/Utilities/PageAsyncResultTypes.cs
cs/test/BlittableLogScanTests.cs
cs/test/GenericLogScanTests.cs
cs/test/LogScanTests.cs

We are adding the ability to scan all entries in the hybrid log between a given logical address range. Note that this is slightly different from key iteration, which would return only the currently active record versions present in the key-value store. The scan feature allows us to go through the entire log using sequential I/O. One may build an IEnumerable or FIFO queue interface for the log using this basic functionality.

[WIP] Scan log given logical address range

---

README.md
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/FASTER/Checkpoint.cs
cs/src/core/Index/FASTER/Recovery.cs

All changes are related to Directory Seperator charector, Windows slash is converted to unix compatible code using `Path.DirectorySeparatorChar` which is platform independant.
I would like to contribute in .Net Core support, Mac OS and Linux areas. Like converting playground area to unix compatible code etc.

Changes making "Faster" file storage support unix folder paths

---

cs/src/core/Allocator/AllocatorBase.cs

Due to HeadOffsetLagNumPages, ReadOnlyLagAddress can be greater than HeadOffsetLagAddress. This change ensures this does not happen.

Ensuring ReadOnlyLagAddress does not exceed HeadOffsetLagAddress

---

cs/benchmark/Functions.cs
cs/playground/ClassCache/Types.cs
cs/playground/ClassSample/Program.cs
cs/playground/StructSample/Functions.cs
cs/playground/StructSampleCore/Functions.cs
cs/playground/SumStore/SumStoreTypes.cs
cs/src/core/Allocator/BlittableScanIterator.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Allocator/GenericScanIterator.cs
cs/src/core/Allocator/IFasterScanIterator.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/FASTERThread.cs
cs/src/core/Index/FASTER/LogAccessor.cs
cs/src/core/Index/Interfaces/FunctionsBase.cs
cs/src/core/Index/Interfaces/IFunctions.cs
cs/test/BasicFASTERTests.cs
cs/test/BlittableLogScanTests.cs
cs/test/GenericDiskDeleteTests.cs
cs/test/GenericLogScanTests.cs
cs/test/ObjectRecoveryTestTypes.cs
cs/test/ObjectTestTypes.cs
cs/test/RecoverContinueTests.cs
cs/test/RecoveryTestTypes.cs
cs/test/SimpleRecoveryTest.cs
cs/test/TestTypes.cs

We are adding native support for the record **Delete** operation in FASTER:
* If the record is in the mutable region, it will be marked with the tombstone bit in header, and value will be overwritten with default.
* If the record is in memory and is pointed to directly by the hash index, we elide the record from the hash chain using a CAS on the index entry to the previous record. The elided record is marked with both a tombstone and an invalid bit in this case.
* If the record is in read-only or earlier region, we will add a new tombstone record to the end of the hash chain to identify the deleted record.
Note that from the perspective of recovery and CPR, deletes behave similarly to Upserts.
This checkin will replace the prior experimental method of `DeleteFromMemory`.

Supporting Deletes in FASTER

---

cs/benchmark/FasterYcsbBenchmark.cs
cs/playground/SumStore/RecoveryTest.cs
cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/BlittableAllocator.cs
cs/src/core/Allocator/BlittableScanIterator.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Allocator/GenericScanIterator.cs
cs/src/core/Allocator/MallocFixedPageSize.cs
cs/src/core/Device/ManagedLocalStorageDevice.cs
cs/src/core/Epochs/FastThreadLocal.cs
cs/src/core/Epochs/LightEpoch.cs
cs/src/core/Index/FASTER/Checkpoint.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERBase.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/FASTERThread.cs
cs/src/core/Index/FASTER/LogAccessor.cs
cs/src/core/Index/FASTER/Recovery.cs
cs/src/core/Index/Interfaces/IFasterKV.cs
cs/src/core/Utilities/BufferPool.cs
cs/src/core/Utilities/PageAsyncResultTypes.cs
cs/test/ComponentRecoveryTests.cs
cs/test/FullRecoveryTests.cs
cs/test/ObjectRecoveryTest.cs

We have used ThreadStatic until now, for storing thread-local variables. This does not work when you have multiple instances of FASTER operating at the same time. This PR fixes the problem by using instance-specific thread-local variables instead. We have implemented our own version of thread-local for this purpose, called FastThreadLocal<T>. Incidentally, FastThreadLocal<T> is optimized to be around 10x faster than ThreadLocal<T> in our micro-benchmarks. There is a configurable (in code) limit of 128 instances of a particular thread-local variable type. This may be relaxed in future if the requirement comes up. With this PR, there are no shared objects between instances, except for the buffer pool which is shared static for the entire process.

Removing statics from codebase

---

cs/src/core/Index/FASTER/FASTERThread.cs

Changing the spin-wait technique to Yield in AsyncGetFromDisk greatly improved performance. Adding analogous change to InternalCompletePending.

Add yield to complete pending

---

cc/benchmark-dir/benchmark.cc

What:
* remove misleading comment
Why:
* the benchmark uses a FileSystemDisk not a NullDisk as implied by this
comment

cc: benchmark: remove misleading comment

---

cs/src/core/Index/FASTER/Checkpoint.cs

Currently, all index checkpoints are disallowed if ReadCache is enabled. This change allows the checkpoint as long as the ReadCache has not yet been used.

Allow checkpoint if read cache is unused

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/BlittableScanIterator.cs
cs/src/core/Allocator/GenericScanIterator.cs
cs/src/core/Allocator/IFasterScanIterator.cs
cs/src/core/Index/FASTER/Extensions.cs
cs/src/core/Index/FASTER/LogAccessor.cs
cs/test/BlittableLogScanTests.cs
cs/test/GenericLogScanTests.cs

This PR allows users to register a user-defined callback, which is invoked when records in the hybrid log become read-only. It can be used for various reasons:
(1) to perform data write-through to an external store
(2) to perform stream processing on the change log created by the key-value store
How it Works
---------------
The FASTER log accessor now supports the `IObservable<IFasterScanIterator<Key, Value>>` interface. This means you can `Subscribe` to FASTER log, in order to receive (as push calls) updates whenever records enter the read-only region of the hybrid log:
```cs
var s = fht.Log.Subscribe(new LogObserver());
...
s.Dispose();
```
The parameter `LogObserver` is an instance of type `IObserver<IFasterScanIterator<Key, Value>>`. User gets push-based callbacks via the `OnNext` …

Support for callback when records in hybrid log become read-only

---

cs/src/core/Device/LocalStorageDevice.cs
cs/src/core/Utilities/Native32.cs
cs/test/SharedDirectoryTests.cs

Currently, two faster instances cannot share the same log directory and also specify deleteOnClose. Adding the FILE_SHARE_DELETE flag allows this, and ensures the files persist until all handles across instances have closed. Also adding a test to validate this workflow.

Adding FILE_SHARE_DELETE when deleteOnClose is used

---

cc/benchmark-dir/benchmark.cc
cc/playground/sum_store-dir/sum_store.h
cc/src/core/faster.h
cc/src/core/internal_contexts.h
cc/test/in_memory_test.cc
cc/test/paging_test.h
cc/test/recovery_test.h

What:
* add a `value_size()` method that allows the user to compute the new Value size with respect to the old Value
* update tests etc to include the new method in `RmwContext`
* add a test to show the use of this method for a growing string
Why:
* supports RMW operations for a "growing" type such as a string, vector
Closes #136

[c++] Add a new `value_size()` method to `RmwContext` for RCU operations

---

cs/src/core/Device/LocalStorageDevice.cs

Removing direct call of callback when IO completes synchronously - we expect the OS to call the callback in this case.
Fix #135

Removing direct call of callback when IO completes synchronously

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/BlittableAllocator.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Allocator/VarLenBlittableAllocator.cs
cs/src/core/Device/LocalStorageDevice.cs
cs/src/core/Index/Common/AddressInfo.cs
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/FASTER/Checkpoint.cs
cs/src/core/Index/FASTER/Recovery.cs
cs/src/core/Utilities/BufferPool.cs

The logic for reading records in the presence of an object log was writing directly to a pinned array of managed objects, to avoid fine grained copy of parts of the log that are not managed. However, this solution has problems in the presence of GC. This checkin primarily undoes this optimization for the sake of correctness. There are a few other minor improvements, such as using a SafeConcurrentDictionary to store file handles, to avoid spurious creation when many threads read in parallel.

Object log recovery fixes

---

azure-pipelines.yml
cc/test/in_memory_test.cc

Currently, the example code has branches that do the opposite to what
the condition implies should happen. As a result, non-replaced records
are being marked as replaced and causing unnecessary read-copy-updates.
I discovered a bug in `faster-rs` where we were using the original logic and were performing subsequent RCU operations even though the values were being updated in-place.

[c++] in_memory_test: fix inverted rmw replace condition

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/Recovery/Checkpoint.cs
cs/src/core/Index/Recovery/Recovery.cs

Fix recovery logic to correctly read back current page, and include begin address in recovery info.
Fix https://github.com/microsoft/FASTER/issues/165

Fix recovery logic to read back page, include begin address

---

cc/src/core/faster.h
cc/src/core/persistent_memory_malloc.h

What:
* expose an optional parameter controlling whether to pre-allocate pages for the `HybridLog`'s in-memory portion
Why:
* prevent latency spike when new page being allocated

[c++] allow users to pre-allocate HybridLog

---

cs/playground/FasterLogSample/Program.cs
cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/BlittableAllocator.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Allocator/VarLenBlittableAllocator.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FasterLog/FasterLog.cs
cs/src/core/Index/FasterLog/FasterLogIterator.cs
cs/src/core/Index/FasterLog/FasterLogSettings.cs
cs/src/core/Index/Recovery/Recovery.cs

* Adding support for low memory footprint (4 pages)
* Added support for odd-sized payloads in presence of holes in log
* Fixed concurrency issue that occurs with low num of pages
* Improved max throughput by eliminating a 10ms sleep in BlockAllocate
* Misc cleanup of logic to track flush and close addresses in log

Fasterlog lowmem

---

README.md

the package is now hosted at https://www.nuget.org/packages/Microsoft.FASTER/

Fix nuget links

---

cc/src/core/key_hash.h
cc/test/in_memory_test.cc
cc/test/recovery_test.h
cc/test/test_types.h

This is a small refactoring of tests for C++ version of FASTER.

[C++][tests] Extract common (simple) key and value definitions for reuse

---

cs/src/core/Index/FasterLog/FasterLog.cs
cs/src/core/Index/FasterLog/FasterLogIterator.cs
cs/src/core/Utilities/Utility.cs

- Added a WithCancellationAsync method to make all the awaits respect a user provided cancellation token
- In cases where exceptions were getting swallowed from the awaited task, added checks to make sure OperationCanceledExceptions bubble up to the caller

[FasterLog] Add support for Cancellation tokens on all the async APIs

---

cs/playground/FasterLogSample/Program.cs
cs/src/core/Index/FasterLog/FasterLog.cs

Clarified TruncateUntil caveat in comment, for user providing a valid until address. Added a safer variant: TruncateUntilPageStart.
Fix https://github.com/microsoft/FASTER/issues/191

Clarified TruncateUntil, added TruncateUntilPageStart

---

cc/test/in_memory_test.cc

The more common code that creates threads is extracted as a common helper function.
In the second commit, the helper function is hardened to launch threads simultaneously by a latch.

[C++] Harden concurrent in_memory_test tests

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/Device/IDevice.cs
cs/src/core/Device/LocalStorageDevice.cs
cs/src/core/Device/ManagedLocalStorageDevice.cs
cs/src/core/Device/StorageDeviceBase.cs
cs/src/core/Index/Recovery/Checkpoint.cs
cs/src/core/Index/Recovery/Recovery.cs
cs/src/core/Utilities/PageAsyncResultTypes.cs

* Fix CompletePending to not hold epoch
* Fix object log initialization to set segment size to -1 so that device does not pre-allocate/truncate object log segments to a fixed size
Ref https://github.com/microsoft/FASTER/pull/215
Fix https://github.com/microsoft/FASTER/issues/227
Fix https://github.com/microsoft/FASTER/issues/225

Fix complete-pending & segment sizes for object log

---

cc/src/core/faster.h

We have some application code including faster.h, and found that inline definitions for the new gtest print support functions reduce our build situations of linker error for multiple defns. There is a decent chance for collisions on the "<<" operator defn depending on what other c++ libraries are included in the application code.
Linux, C++, g++ 7.4

inline gtest print support function defns

---

cs/playground/FasterKVAsyncSample/Program.cs
cs/src/core/ClientSession/ClientSession.cs
cs/test/ObjectFASTERTests.cs

Attempts to fix #239 .
If the Functions class depends on the Context instance, async methods will make it fail with a Null Reference Exception.
As per #238, full adherence to TLP semantics would see callbacks on the Functions class gone, maybe replaced by injected middleware semantics, ASPNET.CORE style.

User should be able to provide context class when using async methods

---

cs/playground/FasterKVAsyncSample/Program.cs
cs/src/core/ClientSession/ClientSession.cs
cs/test/ObjectFASTERTests.cs

Async methods do not support ref Keys, wich are needed when using the unsafe var length strategy.
They could.

Ref keys on async methods

---

cs/src/core/Index/FasterLog/FasterLogIterator.cs
cs/test/FasterLogTests.cs

Here is a proposed overload of FasterLogIterator.GetNext which also has an _out nextAddress_ with a simple test case. GetNextInternal was also updated for it.
Sending for your consideration. I also am not a regular user of GitHub, so apologies if this comes out wrong.
Thanks!
Resolves microsoft/FASTER#244

Added overload of GetNext() that also returns next address

---

cs/src/core/Index/Synchronization/VersionChangeStateMachine.cs

After yesterday's discussion, I think we missed this on the previous PR.

Skip WAIT_PENDING check if using relaxed CPR

---

azure-pipelines.yml
cs/benchmark/FASTER.benchmark.csproj
cs/playground/ClassCache/ClassCache.csproj
cs/playground/ClassCacheMT/ClassCacheMT.csproj
cs/playground/ClassRecoveryDurablity/ClassRecoveryDurablity.csproj
cs/playground/ClassSample/ClassSample.csproj
cs/playground/FasterKVAsyncSample/FasterKVAsyncSample.csproj
cs/playground/FasterKVDiskReadBenchmark/FasterKVDiskReadBenchmark.csproj
cs/playground/FasterLogSample/FasterLogSample.csproj
cs/playground/FixedLenStructSample/FixedLenStructSample.csproj
cs/playground/PeriodicCompaction/PeriodicCompaction.csproj
cs/playground/StructSample/StructSample.csproj
cs/playground/StructSampleCore/StructSampleCore.csproj
cs/playground/SumStore/SumStore.csproj
cs/playground/VarLenStructSample/VarLenStructSample.csproj
cs/src/core/FASTER.core.csproj
cs/src/core/FASTER.core.debug.nuspec
cs/src/core/FASTER.core.nuspec
cs/src/devices/AzureStorageDevice/FASTER.devices.AzureStorageDevice.csproj
cs/src/devices/AzureStorageDevice/FASTER.devices.AzureStorageDevice.nuspec
cs/test/FASTER.test.csproj

This PR:
- Adds build target for .NETSTANDARD 2.1 and simplifies dependencies for .NETCOREAPP3.1 & NET5.0
- Increases the minimum .NETFramework version to 4.6.1. Several dependent libraries dropped net46.
- Updates the nuget packages to their latest versions
- Updates playground samples to .NETCOREAPP3.1

Cross target .NETSTANDARD2.1 and update playground examples to .NETCOREAPP3.1

---

cs/README.md
docs/README.md

Hello Microsoft,
There were some outdated NuGet links to an old package in your README.md files. This PR changes the outdated NuGet links to the current NuGet link: https://www.nuget.org/packages/Microsoft.FASTER
Thanks,
Brian Chavez

Update other README.md docs with correct NuGet download link.

---

cs/src/core/Device/LocalStorageDevice.cs
cs/src/core/Utilities/SafeConcurrentDictionary.cs
cs/test/SharedDirectoryTests.cs

In ASA's reference data workflow, we must create new FASTER instances and thus new devices regularly. We also must prepopulate log file handles to satisfy some requirements for our multi-tentant service. Currently, we create a new LocalStorageDevice, then add each file handle with GetOrAddHandle, which inserts to a ConcurrentDictionary, and when the count of these files reach the thousands, this prepopulation can take upwards of 10s of seconds. This change allows us to prepopulate the ConcurrentDictionary with a flat array, eliminating this latency.

Prepopulate log file handles

---

cc/src/device/file_system_disk.h
cc/src/device/null_disk.h
cc/src/environment/file_common.h
cc/src/environment/file_linux.cc
cc/src/environment/file_linux.h
cc/src/environment/file_windows.h
cc/test/test_types.h

As mentioned in #266, having a `using namespace` statement in a header file can cause ambiguous references down the line. This PR removes the `using namespace FASTER::core` statement from a header file and adapts the depending source files to use `core::` explicitly.

Remove using namespace from header file

---

cc/src/core/faster.h
cc/src/core/persistent_memory_malloc.h

It seems that when there is less than kHeaderSize immutable pages in log,
we will not be able to dump the in-memory log into disk when the in-memory
log is full. Added a check to enforce this requirement.
A complication is compaction logic. In compaction logic, the logic makes
sure that nothing will be dumped to disk, so it provides no backing storage
path (the root_directory is "") and the requirement does not apply.
So we will only throw error if root_directory is not "".

Make sure we have at least kHeaderSize immutable pages in log

---

cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERLegacy.cs
cs/src/core/Index/Synchronization/FullCheckpointStateMachine.cs
cs/src/core/Index/Synchronization/HybridLogCheckpointTask.cs
cs/src/core/Index/Synchronization/IndexSnapshotStateMachine.cs

Fix https://github.com/microsoft/FASTER/issues/281

Allow checkpoint type to be chosen per instantiation

---

cs/playground/VarLenStructSample/Types.cs
cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/BlittableAllocator.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Allocator/VarLenBlittableAllocator.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/ClientSession/FASTERClientSession.cs
cs/src/core/Index/Common/LogSettings.cs
cs/src/core/Index/Common/VariableLengthStruct.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/FASTERLegacy.cs
cs/src/core/Index/Interfaces/IFasterKV.cs
cs/src/core/Index/Interfaces/IFasterSession.cs
cs/test/VLTestTypes.cs

* Allow users to specify var-len struct settings that are Input-dependent, on a per-session basis, using a new IVariableLengthStruct<T, Input>.
* Remove Input-based methods from IVariableLengthStruct<T> interface.
* Provide default implementation for the Input-dependent functions
GetLenth(Input) -> GetAverageLength()
GetLength(Value, Input) -> GetLength(Value)
Fix https://github.com/microsoft/FASTER/issues/289

Separate out Input-dependent functions by session, for variable length structs

---

cs/src/core/Device/ManagedLocalStorageDevice.cs

Fixes issue on Linux devices, where parallel reads on the same file handle are unsupported. We already sequentialize for Writes, this bugfix applies this to Reads as well.
Conversation at https://github.com/microsoft/FASTER/issues/309

[C#] Fix issue with parallel reads on Linux storage devices

---

cs/src/core/Device/ManagedLocalStorageDevice.cs
cs/src/core/FASTER.core.csproj
cs/src/core/FASTER.core.nuspec

Remove dependency on `Mono.Posix.NETStandard`. It was used only to disable file read caching on non-Windows. This "feature" does not justify adding another dependency, as it is creating issues with cross-platform Xamarin apps.

[C#] Remove dependency on Mono.Posix.NETStandard

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Device/Devices.cs
cs/src/core/Index/Common/LogSettings.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERIterator.cs
cs/src/core/Index/FASTER/LogAccessor.cs
cs/src/core/Index/Recovery/IndexRecovery.cs
cs/src/core/Index/Recovery/Recovery.cs

* Allow recovery without index checkpoint, by simply using an empty hash table and replaying the log from the begin address
* Add checks to make sure users do not instantiate FASTER without creating log devices

[C#] Allow recovery without index checkpoint

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Index/FASTER/FASTERBase.cs
cs/src/core/Index/FasterLog/FasterLog.cs
cs/src/core/Index/Interfaces/NullFasterSession.cs
cs/src/core/Index/Recovery/IndexRecovery.cs
cs/src/core/Index/Recovery/Recovery.cs
cs/test/AsyncLargeObjectTests.cs
cs/test/AsyncTests.cs
cs/test/GenericDiskDeleteTests.cs
cs/test/RecoveryChecks.cs
cs/test/SessionFASTERTests.cs

This PR significantly speeds up recovery (from checkpoint), which is important in several scenarios.
* Allow calling recover multple times with newer hlog checkpoints
* Fix bug in index fast-forward when using snapshot checkpoints with separate index checkpoints
* Recovery from snapshot leaves the log mutable after recovery
* Avoid rescanning the log during recovery - only single scan of the log is now needed
* Only write back pages that have records that need to be marked as Invalid
* Do not write back from snapshot file to main log during recovery as it should remain as mutable unpersisted state

[C#] Recovery improvements

---

cs/samples/FasterLogPubSub/Program.cs
cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Index/FasterLog/FasterLog.cs
cs/src/core/Index/FasterLog/FasterLogIterator.cs
cs/src/core/Index/FasterLog/FasterLogSettings.cs

* Enables capability for a different process to consume (iterate or tailing scan) FasterLog in read-only mode
* With this, we can have one committing process and another consuming process for the log entries
* The way this is accomplished is by allowing the read-only iterating instance to continuously "recover" using the commits written out by the primary FasterLog writer
* When used with `AzureStorageDevice`, the enqueuing/committing process and the consuming process may be on different machines, and approximately emulates Kafka/EventHubs behavior.
Sample usage: [here](https://github.com/microsoft/FASTER/blob/fasterlog-separate-scan/cs/samples/FasterLogPubSub/Program.cs)
Inline sample:
```cs
static async Task SeparateConsumerAsync(CancellationToken cancellationToken)
{
var device = …
```

[C#] Support FasterLog scan from different process

---

cs/FASTER.sln
cs/samples/SecondaryReaderStore/Program.cs
cs/samples/SecondaryReaderStore/SecondaryReaderStore.csproj
cs/src/core/Allocator/BlittableAllocator.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/Interfaces/IFasterKV.cs
cs/src/core/Index/Recovery/Recovery.cs

* Sample to show read-only secondary reader store constantly catching up to primary store
* Add recovery option to recover without writing undo (useful for read-only secondaries)

[C#] Sample for read-only secondary KV store continuously recovering to primary's log/checkpoints

---

cs/samples/StoreAsyncApi/Program.cs
cs/samples/StoreDiskReadBenchmark/Program.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/ClientSession/FASTERAsync.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/FASTERThread.cs
cs/src/core/Index/Interfaces/ICompactionFunctions.cs
cs/src/core/Index/Recovery/Recovery.cs
cs/test/AsyncTests.cs
cs/test/BlittableIterationTests.cs
cs/test/FunctionPerSessionTests.cs
cs/test/GenericIterationTests.cs
cs/test/ObjectFASTERTests.cs
cs/test/RecoverContinueTests.cs
cs/test/SimpleAsyncTests.cs
cs/test/StateMachineTests.cs

* Async version of RMW that returns status
* Improved async Read to share code with sync path
Using async RMW:
Version 1:
```cs
var status = (await session.RMWAsync(ref key, ref input)).CompleteRMW();
```
Version 2:
```cs
var r = await session.RMWAsync(ref key, ref input);
while (r.status == Status.PENDING)
r = await r.CompleteRMWAsync();
```
Version 2 is truly async even in the rare case that RMW completion has to go pending again. This is exceedingly rare (happens only when some other operation on the same key increments the value AND that value goes back to disk before this RMW could complete its `CompleteRMW`). Therefore we offer a easier version 1 just does this rare pending work synchronously, in order to keep a much simpler API.
Related issues and PRs:
* …

[C#] Async version of RMW that returns status

---

cs/src/core/Index/FASTER/FASTERImpl.cs

Create `TaskCompletionSource` with `TaskCreationOptions.RunContinuationsAsynchronously` (all other places already do that). I noticed the error when I tried to run a highly async code (hundreds/thousands of tasks reading from faster) and hit a "deadlock", all (> 30) threads were in 
```
while (device.Throttle())
{
Thread.Yield();
epoch.ProtectAndDrain();
}
```
My guess is that thread pool was exhausted thus IO completion callbacks for reading from disk were unable to be scheduled. This happened because call to `TaskCompletionSource.TrySetResult` might try to execute the continuations in the same thread (in the thread pool) and `ReadAsync` indirectly leads to the code above. As we are exclusively using the thread we might hit a point where all thread pool threads are "unavailable" for IO …

Fixed task completion source to run continuations asynchronously.

---

cs/samples/StoreDiskReadBenchmark/Program.cs
cs/samples/StoreDiskReadBenchmark/Types.cs
cs/src/core/Epochs/LightEpoch.cs
cs/src/core/Index/Interfaces/IFunctions.cs
cs/src/core/Index/Synchronization/StateTransitions.cs

* Avoid recursive call in SuspendDrain to prevent stack overflow
* Change epoch draining code to first decrement drainCount, then perform trigger_action. This should be safe, and improve performance as well.
CC @tli2
Fix https://github.com/microsoft/FASTER/issues/341

[C#] Fix StackOverflow during CompleteCheckpointAsync

---

cs/src/core/ClientSession/ClientSession.cs
cs/src/core/Index/FASTER/FASTERImpl.cs

- Streamline DeleteInternal handling of mutable records
- Assert SupportAsync in ClientSession ReadAsync and RMWAsync methods
- Eliminate code duplication on Read overload without Input
Fix https://github.com/microsoft/FASTER/issues/336

[C#] Dispose ClientSessions from FasterKV. Also:

---

cs/src/core/ClientSession/ClientSession.cs

Adding ref-free overloads to FASTER operations, to further simplify user experience. Here is a sample:
```cs
using var store = new FasterKV<long, string>(1L << 20, new LogSettings { LogDevice = new NullDevice(), ObjectLogDevice = new NullDevice() });
using var s = store.NewSession(new SimpleFunctions<long, string>((a, b) => a + b));
s.Upsert(1, "one");
s.Upsert(2, "two");
// Read with out param for Output, returns Status
s.Read(2, out string r);
if (r != "two")
Console.WriteLine("Error");
s.RMW(2, "two");
// Read returns (Status, Output)
if (s.Read(2) != (Status.OK, "twotwo"))
Console.WriteLine("Error");
s.Delete(1);
if (s.Read(1, out _) != Status.NOTFOUND)
Console.WriteLine("Error");
```

[C#] Adding ref-free overloads to FASTER operations

---

cs/samples/HelloWorld/Program.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/FASTERLegacy.cs
cs/src/core/Index/FASTER/LogCompactionFunctions.cs
cs/src/core/Index/Interfaces/FunctionsBase.cs
cs/src/core/Index/Interfaces/IFunctions.cs
cs/src/core/Index/Interfaces/TryAddFunctions.cs
cs/test/AsyncTests.cs
cs/test/NeedCopyUpdateTests.cs
cs/test/ObjectRecoveryTest2.cs
cs/test/ObjectRecoveryTestTypes.cs
cs/test/ObjectTestTypes.cs
cs/test/RecoverContinueTests.cs
cs/test/RecoveryTestTypes.cs
cs/test/SimpleRecoveryTest.cs
cs/test/TestTypes.cs
cs/test/VLTestTypes.cs

The PR adds a `NeedCopyUpdate` callback to `IFunctions` for RMW, which the application can use to determine if they want to proceed with a log allocation + `CopyUpdater`. The default for this callback is `true`.
In order to force cascading into `NeedCopyUpdate`, application can just return `false` for `InPlaceUpdater`.
This will avoid unnecessary allocation if we do not need to `CopyUpdate`. The decision is made based on old value and input.
Example use cases:
* Implementing `TryAdd` functionality using RMW
* Implementing a `key->set|hash` structure (similar to redis set or even hash). We want to be able to prevent a copy if the item being added to a set is already present, otherwise if it is missing then we need to modify the set, so a copy is required. 
See linked issue below for more …

[C#] Added NeedCopyUpdate to IFunctions for RMW

---

cs/benchmark/FasterYcsbBenchmark.cs
cs/benchmark/Program.cs

Add command-line option `-k` / `--backup` to replace constants in `FASTER.benchmark`. Used to enable Backup and Restore of FasterKV for fast test startup. Values:
* 0 = None; Populate FasterKV from source data (the default)
* 1 = Recover FasterKV from Checkpoint; if this fails, populate FasterKV from source data
* 2 = Checkpoint FasterKV (unless it was Recovered by option 1; if option 1 is not specified, this will overwrite an existing Checkpoint)
* 3 = Both (Recover FasterKV if the Checkpoint is available, else populate FasterKV from source data and Checkpoint it so it can be Restored in a subsequent run)
These options do not apply when periodic checkpointing is turned on.

[C#] Benchmark settings to backup & restore database for quicker runs

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/VarLenBlittableAllocator.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/ClientSession/FASTERClientSession.cs
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/Common/HeapContainer.cs
cs/src/core/Index/Common/VariableLengthStruct.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/FASTERLegacy.cs
cs/src/core/Index/FASTER/FASTERThread.cs
cs/src/core/Index/Interfaces/IFasterKV.cs
cs/src/core/Index/Interfaces/IFasterSession.cs

Add support for variable-length `Input` type when creating a new session, via `SessionVariableLengthStructSettings` parameter.

[C#] Support variable length Input

---

cs/src/core/ClientSession/ClientSession.cs
cs/src/core/ClientSession/FASTERAsync.cs

* Capture exceptions during ReadAsync and RMWAsync await to be processed during Complete()
* Remove op from ctx.pendingReads only after Complete() is done
This will also prevent concurrent access to ctx.ioPendingRequests in case an I/O exception occurs during an async I/O operation.

[C#] Capture async exceptions correctly

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/BlittableScanIterator.cs
cs/src/core/Allocator/GenericScanIterator.cs
cs/src/core/Allocator/IFasterScanIterator.cs
cs/src/core/Allocator/VarLenBlittableScanIterator.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/Index/FASTER/FASTERIterator.cs
cs/src/core/Index/FASTER/LogAccessor.cs
cs/test/BlittableLogCompactionTests.cs
cs/test/GenericLogCompactionTests.cs
cs/test/MemoryLogCompactionTests.cs

`session.Compact` can now accept addresses that are not at strict record boundaries. It will return the actual address until which compaction was completed (next nearest record boundary).
For example, you can compact 20% of the log as follows:
```cs
long compactUntil = store.Log.BeginAddress + (store.Log.TailAddress - store.Log.BeginAddress) / 5;
compactUntil = session.Compact(compactUntil, shiftBeginAddress: false);
await store.TakeHybridLogCheckpointAsync(CheckpointType.FoldOver);
store.Log.ShiftBeginAddress(compactUntil);
```
See documentation [here](https://github.com/microsoft/FASTER/blob/master/docs/cs/FasterKV.md#log-compaction).
Also, added option to `ShiftBeginAddress`, to snap given address to nearest earlier page start.

[C#] Allow log compaction to non-record-boundary addresses

---

cs/benchmark/FasterYcsbBenchmark.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERBase.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/Recovery/IndexRecovery.cs
cs/src/core/Index/Synchronization/IndexResizeStateMachine.cs
cs/test/RecoveryChecks.cs

Fixed `GrowIndex()` to work correctly, and return only after index size doubling is complete. For examples on using `GrowIndex` with checkpointing, search for GrowIndex in https://github.com/microsoft/FASTER/blob/master/cs/test/RecoveryChecks.cs
Fix https://github.com/microsoft/FASTER/issues/393

Fixed GrowIndex to work correctly

---

cs/src/core/Index/Common/RecordInfo.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/RecordAccessor.cs
cs/src/core/Utilities/IntExclusiveLocker.cs
cs/test/LockTests.cs

Add RecordInfo.SpinLock
Fix SingleReader call for readcache to pass kInvalidAddress

Record locking

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/BlittableAllocator.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Allocator/VarLenBlittableAllocator.cs
cs/src/core/Index/FASTER/LogAccessor.cs

* Gets the size per record (only the fixed-size part) on the main log
* For C# class objects, only counts the reference size (8 bytes) and not the actual heap object size
* Does not include the size of inline variable-length struct (varlen) objects on the log
* Usage: `var size = store.Log.FixedRecordSize`

[C#] Added store.Log.FixedRecordSize API

---

cs/src/core/Index/FASTER/FASTERIterator.cs

In some occasions iter2 is null, which leads to not disposing any other members. This check only disposes members when they are not null.

fix(iterator): null conditional dispose

---

cs/benchmark/FasterYcsbBenchmark.cs
cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Device/Devices.cs
cs/src/core/Device/IDevice.cs
cs/src/core/Device/LocalStorageDevice.cs
cs/src/core/Device/ManagedLocalStorageDevice.cs
cs/src/core/Device/StorageDeviceBase.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/FASTERIterator.cs
cs/src/core/Index/FASTER/FASTERThread.cs
cs/src/core/Utilities/Native32.cs
cs/test/SharedDirectoryTests.cs

The C# ThreadPool binding based disk I/O (`ThreadPool.Bind(handle)`) in FASTER was found to not scale well beyond around 500K ops/sec, so we have added our own implementation of I/O Completion Port based I/O handling. This is only for `LocalStorageDevice` on Windows systems. This gives excellent scalability for disk-bound use cases.
*Setup*: YCSB benchmark with 250 million tuples (8 byte keys and values), database pre-loaded, 100% read workload, uniform random keys, all data served from disk (no memory used by log).
*Disk*: Dell Express Flash NVMe PM1725 3.2TB AIC
*Results*:

[C#] Support IOCP-based operations in LocalStorageDevice

---

cs/src/core/Index/FasterLog/FasterLogIterator.cs

make FasterLogScanIterator read behavior consistent across the following two flows:
1.
a. caller initiates GetNext
b. Log gets disposed
2.
a. Log gets disposed
b. a GetNext is initiated
In flow 1 today, we get a return-value of false from GetNext, whereas
In flow 2 today, we get an ObjectDisposedException.

make FasterLogScanIterator read behavior consistent in the face of iterator disposal

---

cs/src/core/Device/FixedPool.cs
cs/src/core/Device/LocalStorageDevice.cs
cs/src/core/Device/ManagedLocalStorageDevice.cs
cs/src/core/Index/CheckpointManagement/DeviceLogCommitCheckpointManager.cs
cs/test/FasterLogTests.cs

Fix https://github.com/microsoft/FASTER/issues/417

[C#] Support concurrent device dispose and async commit

---

cs/benchmark/ConcurrentDictionaryBenchmark.cs
cs/benchmark/FasterSpanByteYcsbBenchmark.cs
cs/benchmark/FasterYcsbBenchmark.cs
cs/benchmark/Functions.cs
cs/benchmark/Options.cs
cs/benchmark/Program.cs
cs/benchmark/TestLoader.cs
cs/benchmark/TestStats.cs
cs/benchmark/YcsbConstants.cs
cs/benchmark/ZipfGenerator.cs

Refactor YCSB benchmark:
- Move constants and code out of program.cs into Options.cs, YcsbConstants.cs
- Move constants from the test classes to YcsbConstants.cs
- Add ZipfGenerator.cs to generate synthetic data in Zipf distribution
- Move LoadData logic from test classes to TestLoader.cs and hold the keys to be shared across iterations (see new -i param)
- Move backup/recover logic from test classes to TestLoader.cs
- Added commandline-arg verification to TestLoader.cs
- Add TestStats.cs to report summary stats across iterations (see new -i param): mean ins/sec (load) or ops/sec (experiment), stdev, stdev as % of mean
- Formatted output for improved parsability, to include all relevant commandline args (for charting etc)
- Update commandline options:
- Modify -k (and change the full …

[C#] Performance benchmark refactor

---

cs/src/core/Index/FASTER/FASTERImpl.cs

Refactor InternalUpsert and InternalRmw to move latch-acquisition and new-record logic to separate routines, enabling inlining and better optimization of these functions

[C#] Improve Upsert and RMW performance

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/PendingFlushList.cs
cs/src/core/Device/FixedPool.cs
cs/src/core/Device/ManagedLocalStorageDevice.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FasterLog/FasterLog.cs
cs/test/ManagedLocalStorageTests.cs

* Better handling of async tasks in `ManagedLocalStorageDevice` to work efficiently on Linux with large number of tasks.
* Avoid exception on full `PendingFlushList` and instead fail the commit.
* Use locks to correctly invoke `FileStream.ReadAsync` and `FileStream.WriteAsync` in MLSD.
* Merge adjacent unissued commit requests in `PendingFlushList` for improved commit behavior.
* Remove spin from `FixedPool` when no space left, and instead issue new object for immediate disposal.
Fix https://github.com/microsoft/FASTER/issues/434
Fix https://github.com/microsoft/FASTER/issues/433
Co-authored with @hiteshmadan

[C#] MLSD and FasterLog improvements

---

cs/src/core/Index/Common/RecordInfo.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/Synchronization/ISynchronizationStateMachine.cs
cs/src/core/Index/Synchronization/VersionChangeStateMachine.cs

fix #442
Instead of using > or <, check version with:
1.  whether entry in question is in the fuzzy region created by a version shift (e.g., tail of log in checkpoint, where v_new entries could be due to RCU)
2. whether truncated version in record header equals the target version of current version shift.
This should have the same semantic as before (assuming version advances cannot differ by more than 8192) while handling wraparound correctly.
Not sure whether worth writing a test case for as it is very hard to create a buggy wrap-around trace on a unit-test scale.

[C#] Resolve version wrap around

---

cs/samples/MemOnlyCache/CacheSizeTracker.cs
cs/samples/MemOnlyCache/Program.cs
cs/samples/MemOnlyCache/Types.cs
cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/LogAccessor.cs
docs/_docs/23-fasterkv-tuning.md

The FASTER in-memory portion consists of `store.Log.BufferSize` pages in a circular buffer, based on the user-provided log settings of `PageSizeBits` and `MemorySizeBits`.
When FASTER stores C# class objects, these buffer pages contain pointers to reference data which may take different sizes, making the control of total memory footprint of FASTER difficult in this scenario. This is because the total number of pointers in memory remains fixed, based on total memory size.
For example, when `PageSizeBits` is 14 (i.e., each page is 2^14 = 16KB) and `MemorySizeBits` is 25 (i.e., 2^25 = 32MB total memory), we have `BufferSize` is 2048 (i.e., 2^(25-14)) pages in memory. With a total memory size of 32MB, with C# objects as keys and values, since each record takes up 24 bytes (8 byte record …

[C#] Support dynamically varying the allocator log memory usage

---

docs/_docs/40-fasterlog-basics.md

Scope of changes is restricted to docs only.

fix(docs): corrects typo in project documentation

---

cs/src/core/Index/FasterLog/FasterLogIterator.cs
cs/src/devices/AzureStorageDevice/AzureStorageNamedDeviceFactory.cs

WaitAsync should return false if iterator has reached end of scan range:
Fix https://github.com/microsoft/FASTER/issues/477
Fix to path in AzureStorage device factory list contents:
Fix https://github.com/microsoft/FASTER/issues/478

[C#] Fixes to WaitAsync, list Azure device contents

---

cs/src/core/Index/FasterLog/FasterLog.cs
cs/src/core/Index/FasterLog/FasterLogSettings.cs
cs/test/FasterLogResumeTests.cs

Commit file naming is handled automatically by default commit manager.
Fix https://github.com/microsoft/FASTER/issues/490

[C#] Mark LogCommitFile field (FasterLogSettings) as obsolete

---

cs/remote/samples/FixedLenClient/Program.cs
cs/remote/samples/VarLenClient/CustomTypeSamples.cs
cs/remote/src/FASTER.client/ClientSession.cs
cs/remote/src/FASTER.client/FixedLenSerializer.cs
cs/remote/src/FASTER.client/MemoryParameterSerializer.cs
cs/remote/src/FASTER.common/IClientSerializer.cs
cs/remote/src/FASTER.common/IServerSerializer.cs
cs/remote/src/FASTER.common/MessageType.cs
cs/remote/src/FASTER.server/BinaryServerSession.cs
cs/remote/src/FASTER.server/FasterKVServer.cs
cs/remote/src/FASTER.server/FixedLenSerializer.cs
cs/remote/src/FASTER.server/SpanByteClientSerializer.cs
cs/remote/src/FASTER.server/SpanByteSerializer.cs
cs/remote/src/FASTER.server/SpanByteServerSerializer.cs
cs/remote/src/FASTER.server/SubscribeKVBroker.cs

This PR contains code with features added as follows:
1. Support publish to push to multiple BinaryServerSessions per key
2. Add publish call to RMW on BinaryServerSession
3. Publish uses a dedicated Start task that retrieves keys from async queue and calls publish on sessions
4. If same key occurs multiple times in the async queue, we can send push just for the last one
5. Ensuring that pub/sub is not used for normal operations
6. Added separate samples in FixedLenClient and VarLenClient
7. Handle cleanup of subscription list when a client session disconnects

Added support in Subscriptions. TODO: prefix matching for subscriptions, publish deletes to keys

---

README.md

...because we only referred to the master repo in the SIGMOD talks.

Add a link to the DPR branch

---

cs/remote/samples/VarLenServer/Program.cs
cs/remote/src/FASTER.server/SpanByteClientSerializer.cs
cs/remote/src/FASTER.server/SpanByteFasterKVProvider.cs
cs/remote/src/FASTER.server/SpanByteServerSerializer.cs
cs/remote/test/FASTER.remote.test/VarLenServer.cs
cs/src/core/VarLen/SpanByteAndMemory.cs

This PR adds a specialized remote provider called SpanByteFasterKVProvider that is optimized for `SpanByte` as `Key`, `Value`, `Input`; and `SpanByteAndMemory` as `Output`.
Changes in the PR:
1. Addition of `SpanByteFasterKVProvider.cs`
2. Separation of `SpanByteSerializer` to `SpanByteServerSerializer` and `SpanByteClientSerializer`

[C#] SpanByteFasterKVProvider

---

cs/src/core/Device/LocalMemoryDevice.cs
cs/src/core/Index/FasterLog/FasterLog.cs
cs/src/core/Index/FasterLog/FasterLogSettings.cs
cs/src/core/VarLen/SpanByte.cs
cs/src/core/VarLen/SpanByteAndMemory.cs

Includes another feature:
* Convert serialized `SpanByte` into its non-serialized form, which is a normal value-type struct that include a length header and a pointer to the (same) raw payload bytes. This non-serialized form is safe to heap-copy as long as the underlying payload is fixed.
Fix https://github.com/microsoft/FASTER/issues/518

[C#] Support FasterLog commit dir specification in settings

---

cc/src/core/address.h
cc/src/core/faster.h
cc/test/paging_test.h

The bug is related to how the in-memory trace back of the hash index chain was performed. During testing, the following assertion (L1609 -- now L1619) was not true:
```C++
assert(address < hlog.begin_address.load() || address == pending_context->entry.address());
```
The in-memory trace back of the hash index chain was ignoring the case where the `pending_context->entry.address()` (aka expected entry address) was  greater than the head address, **and** there was no full key match in `[expected entry address, tail address]`. In this case, the trace back would continue past the expected entry address, until either found a record with the same key and address greater or equal to the head address, or reached a record with address less than the head address. Therefore, it was possible for the …

[C++] Rmw bugfix

---

cs/remote/src/FASTER.server/BinaryServerSession.cs
cs/remote/src/FASTER.server/ConnectionArgs.cs
cs/remote/src/FASTER.server/FasterKVServerSessionBase.cs
cs/remote/src/FASTER.server/FasterServer.cs
cs/remote/src/FASTER.server/ServerSessionBase.cs
cs/remote/src/FASTER.server/SpanByteServerSerializer.cs
cs/src/core/VarLen/SpanByte.cs
cs/src/core/VarLen/SpanByteComparer.cs
cs/test/SpanByteTests.cs

* `SpanByte` now supports optional extra metadata in the payload (as first 8 bytes of payload), uses 1 bit in `SpanByte` header to indicate that metadata is present in the payload. This makes its max size as 256MB
* Read payload without metadata using `SpanByte.AsSpan()`
* Read payload with metadata using `SpanByte.AsSpanWithMetadata()`
* Read length of payload with metadata, using `SpanByte.Length`
* Read length of payload excluding metadata, using `SpanByte.LengthWithoutMetadata`
* Get metadata size (0 or 8 bytes) using `SpanByte.MetadataSize`
* Get or set metadata content using `SpanByte.ExtraMetadata`
* Mark existing `SpanByte` as having/not having metadata via `SpanByte.MarkExtraMetadata()` and `SpanByte.UnmarkExtraMetadata()`
This change to `SpanByte` is backwards compatible with …

[C#] SpanByte improvements

---

cs/src/core/Index/FasterLog/FasterLog.cs
cs/test/LogReadAsyncTests.cs

returns an IMemoryOwner<byte> rented from a memorypool rather than a byte array.

MemoryPool-based override for FasterLog.ReadAsync()

---

docs/_docs/25-fasterkv-recovery.md

`(seq % 1L << 20)` = 0 for any `seq`, should be either `seq % (1L << 20)` or `seq % fht.IndexSize`.

Fix typo in 25-fasterkv-recovery.md.

---

cs/src/core/Allocator/IFasterScanIterator.cs
cs/src/core/Allocator/MemoryPageScanIterator.cs
cs/src/core/Allocator/ScanIteratorBase.cs
cs/src/core/Allocator/WorkQueueLIFO.cs
cs/src/core/Index/Common/CompletedOutput.cs
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/Common/HeapContainer.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/FASTERIterator.cs
cs/src/core/Index/Interfaces/IFasterSession.cs
cs/src/core/Index/Recovery/ICheckpointManager.cs
cs/src/core/Index/Recovery/Recovery.cs
cs/test/BasicFASTERTests.cs
cs/test/LockTests.cs
cs/test/ObjectTestTypes.cs
cs/test/RecoveryTestTypes.cs
cs/test/SimpleRecoveryTest.cs

- Add BeginAddress and EndAddress to scan iterators
- Allow null deltaFileDevice in HybridLogCheckpointInfo.Recover
- Rename FoldOverSnapshot to useFoldOverCheckpoint
- Make TakeHybridLogCheckpoint overload call through to overload to avoid duplication
- Add default values to new scanDelta and recoverTo arguments
- Add missing checkpointManager.OnRecovery call to IntenralRecoverAsync
- Shorten a test directory name
- Fix some comments

various changes from indexing work

---

cs/benchmark/FasterSpanByteYcsbBenchmark.cs
cs/benchmark/FasterYcsbBenchmark.cs
cs/benchmark/Program.cs
cs/benchmark/TestLoader.cs
cs/benchmark/YcsbConstants.cs
cs/samples/ReadAddress/VersionedReadApp.cs
cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Async/CompletePendingAsync.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/ClientSession/IClientSession.cs
cs/src/core/Epochs/LightEpoch.cs
cs/src/core/Index/CheckpointManagement/DeviceLogCommitCheckpointManager.cs
cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/Common/RecordInfo.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/FASTER/FASTERThread.cs
cs/src/core/Index/Recovery/Checkpoint.cs
cs/src/core/Index/Recovery/ICheckpointManager.cs
cs/src/core/Index/Recovery/LocalCheckpointManager.cs
cs/src/core/Index/Recovery/Recovery.cs
cs/src/core/Index/Synchronization/FullCheckpointStateMachine.cs
cs/src/core/Index/Synchronization/HybridLogCheckpointTask.cs
cs/src/core/Index/Synchronization/StateTransitions.cs
cs/src/core/Index/Synchronization/VersionChangeStateMachine.cs
cs/src/core/Utilities/PageAsyncResultTypes.cs
cs/test/GenericByteArrayTests.cs
cs/test/ReadAddressTests.cs
cs/test/StateMachineTests.cs

* Use only 1 bit for newVersion in RecordInfo, for CPR. Semantics are that sessions in v+1 will create records in fuzzy region with this bit set. Recovery only scans fuzzy region to elide such records.
* Add 1 Filler bit for future use with fillers in records
* Increase read lock bits to 6 (64 parallel readers)
* Use dirty bit for incremental checkpoints

[C#] Checkpoint, Recovery, RecordInfo updates

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Epochs/LightEpoch.cs
cs/test/LogShiftTailStressTest.cs

Currently, if flush list is full, a new flush will be treated as failure. But this code path is invoked separately from the normal safe guards against out-of-order flushes. This can result in flush failures being swallowed or even non-termination of the commit code path with compound failures.
This PR enforces ordering for failure code path and adds a stress test to guard against regression

[C#] Fix error behavior under frequent commit situations

---

cs/src/core/Index/FasterLog/FasterLog.cs
cs/src/core/Index/FasterLog/FasterLogCommitPolicies.cs
cs/src/core/Index/FasterLog/FasterLogRecoveryInfo.cs
cs/src/core/Index/FasterLog/FasterLogSettings.cs
cs/test/LogShiftTailStressTest.cs

[C#] Fix v2 CommitPolicy Warnings

---

cs/src/core/Allocator/AllocatorBase.cs

Added `TentativeHeadAddress` - we first shift this, and when all threads agree (via epoch bump), we can do some pre-closing work such as eviction. Then we can shift the actual `HeadAddress`, finally closing pages when all threads agree on this (via epoch bump).

[C#] Add TentativeHeadAddress to allocator (v2)

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Async/RMWAsync.cs
cs/src/core/Async/UpdateAsync.cs
cs/src/core/ClientSession/AdvancedClientSession.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/Utilities/CompletionEvent.cs
cs/test/LowMemAsyncTests.cs

Found by Netherite. Fixes:
- Remove 'readonly' from UpdateAsyncInternal._asyncOperation; this was causing the update to _asyncOperation._diskRequest to operate on a copy.
- Also fix call sequence to complete pending I/O in UpdateAsync.Complete()
- Fix the *ClientSession.CompletePendingWithOutput calls
- Make CompletionEvent implement IDisposable

[C#]: Fix NullRef in RMWAsync in low-memory conditions

---

cs/benchmark/FasterSpanByteYcsbBenchmark.cs
cs/benchmark/FasterYcsbBenchmark.cs
cs/playground/ClassRecoveryDurability/Storedb.cs
cs/playground/SumStore/RecoveryTest.cs
cs/remote/src/FASTER.server/Servers/ServerOptions.cs
cs/samples/StoreAsyncApi/Program.cs
cs/src/core/Index/Common/CheckpointSettings.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/Index/Interfaces/IFasterKV.cs
cs/test/AsyncLargeObjectTests.cs
cs/test/AsyncTests.cs
cs/test/GenericDiskDeleteTests.cs
cs/test/GenericIterationTests.cs
cs/test/GenericLogCompactionTests.cs
cs/test/GenericLogScanTests.cs
cs/test/LargeObjectTests.cs
cs/test/MiscFASTERTests.cs
cs/test/NeedCopyUpdateTests.cs
cs/test/ObjectFASTERTests.cs
cs/test/ObjectReadCacheTests.cs
cs/test/ObjectRecoveryTest.cs
cs/test/ObjectRecoveryTest2.cs
cs/test/ObjectRecoveryTest3.cs
cs/test/RecoverContinueTests.cs
cs/test/RecoveryTests.cs
cs/test/SharedDirectoryTests.cs
cs/test/SimpleRecoveryTest.cs
cs/test/StateMachineTests.cs

Users have to specify checkpoint type on a per checkpoint basis.

[C#] Remove CheckpointType from CheckpointSettings (v2)

---

cs/src/core/FasterLog/FasterLog.cs
cs/src/core/FasterLog/FasterLogIterator.cs

Extensions to enqueue SpanByte to FasterLog, and unsafely iterate without memory copy.

[C#] FasterLog v2 advanced user extensions

---

cs/samples/FasterLogSample/Program.cs
cs/src/core/FasterLog/FasterLog.cs
cs/src/core/FasterLog/FasterLogIterator.cs
cs/src/core/FasterLog/FasterLogRecoveryInfo.cs
cs/test/DeviceFasterLogTests.cs
cs/test/FasterLogResumeTests.cs

Logs can be "completed" by enqueuing a special commit records that will interrupt async waiting on async iterators.
Completion persists across restarts and prevents future enqueues.

[C#] FasterLog v2 Add ability to explicitly terminate a log

---

cc/src/core/faster.h

This bugfix is connected to some spurious assertion error messages that may occur during log compaction or log truncation (i.e. `ShiftBeginAddress`).  Example of such an error message is the following: 
```
Assertion `idx < size_' failed.
```
This error message is also mentioned in #582, where a partial solution is proposed, yet it does not fix the underlying issue.

[C++] Bugfix on cleaning hash index buckets

---

cs/src/core/Allocator/MemoryPageScanIterator.cs

I noticed that the fix in #631 did not include the new properties `BeginAddress` and `EndAddress` that were added to MemoryPageScanIterator in v2. 
Since this is a semantic merge conflict it went undetected. This PR is the easy fix.

fix BeginAddress and EndAddress in MemoryPageScanIterator

---

cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/test/DeviceFasterLogTests.cs
cs/test/LockableUnsafeContextTests.cs
cs/test/LowMemAsyncTests.cs
cs/test/ReadCacheChainTests.cs
cs/test/SingleWriterTests.cs
cs/test/TestUtils.cs

- Fixed WriteReason when CTT overrides ReadCache
- make DisableLocking a readonly member
- Call SetTentativeAtomic after Post*
- FIx intermittent failure of BasicHighLatencyDeviceTest

[C#] Various Fixes

---

cs/src/core/Async/RMWAsync.cs

This PR is my attempt at fixing the hanging reads issue. It worked to fix my test, but please review and change if necessary, I am not all that familiar with how the code works.
--- 
Here is a description of the buggy behavior I tracked down:
The RMWAsync.CallInternalRMW executes this line:
internalStatus = InternalRMW(ref key, ref input, ref output, ref context, ref pcontext, fasterSession, currentCtx, serialNo);
And for some reason this returns internalStatus == OperationStatus.ALLOCATE_FAILED. 
This it returns Status.PENDING without first calling HandleOperationStatus.
Because HandleOperationStatus is not called,  this line is not executed:
pendingContext.id = opCtx.totalPending++;
which means that the id keeps its initial value of 0. This is perhaps not an immediate problem (?) …

[C#] Fix hanging reads

---

cc/src/core/guid.h

The line 69 in guid.h was an assignment statement and causing assert failure when running sum_store exe
PS C:\Workspace\FASTER\nbhargava2022\FASTER\cc\build\Debug> .\sum_store.exe single recover "2BACC136-B2CF-4EEA-A1A0-5FB73A14B4EE"
Assertion failed: result = RPC_S_OK, file C:\Workspace\FASTER\nbhargava2022\FASTER\cc\src\core\guid.h, line 69
After the fix, running the same command is successful
PS C:\Workspace\FASTER\nbhargava2022\FASTER\cc\build\Debug> .\sum_store.exe single recover "2BACC136-B2CF-4EEA-A1A0-5FB73A14B4EE"
Test successful
Ran all the unit tests successfully after making the change.

Fixed the comparison in the assert statement

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Index/Recovery/Recovery.cs
cs/src/core/Index/Synchronization/HybridLogCheckpointTask.cs

Fix snapshot checkpoint to set startLogicalAddress to beginning of fuzzy region, instead of to FlushedUntilAddress
Fix snapshot checkpoint recovery to scan only fuzzy region
Also, make serializer take read locks with object log. While this is correct, an optimal solution would:
- take no locks for non-fuzzy records (address < startLogicalAddress)
- take no locks for fuzzy "v" version records (info.InNewVersion = false and address >= startLogicalAddress)
- do not either lock or even serialize (i.e. serialize null) fuzzy "v+1" records (info.InNewVersion = true and address >= startLogicalAddress)

Fix snapshot checkpoint to scan only fuzzy region

---

cs/src/core/FASTER.core.csproj
cs/src/core/FASTER.core.nuspec

When using FASTER and Netherite on a Durable Functions host, the it is not possible to load version 6.0.0 of Microsoft.Extensions.Logging.
This appears to be an instance of a well known problem with the functions host not being able to load the latest versions of some dependencies (https://stackoverflow.com/questions/64809716/could-not-load-file-or-assembly-microsoft-extensions-configuration-abstractions).
Since there is no other workaround for this problem at the moment, we are reverting the versions used by the netstandard2.0 and netstandard 2.1 to Microsoft.Extensions.Logging version 3.1.26 which is the newest one that works.

Use older version of Microsoft.Extensions.Logging for compatibility

---

cs/src/core/ClientSession/LockableUnsafeContext.cs
cs/src/core/ClientSession/UnsafeContext.cs
cs/src/core/Compaction/LogCompactionFunctions.cs
cs/src/core/Index/FASTER/FASTERImpl.cs
cs/src/core/VarLen/SpanByte.cs
cs/src/core/VarLen/SpanByteFunctions.cs

SingleDeleter does not need to set value = default, and for SpanByte this is bad because it zeroes the size of the full SpanByte struct, but we only allocate 4 bytes on the log for the tombstoned record. SpanByteFunctions now overrides FunctionsBase.SingleDeleter to not do this. Also:
- Added pack = 4 to SpanByte so the struct size is the expected 12, not 16
- Made sure temporarily-sealed records are unsealed on readcache skip failure, and fixed one cancellation exit to be before .Sealing the record

[C#] SingleDeleter should not set value = default for SpanByte

---

cs/src/core/ClientSession/ClientSession.cs
cs/src/core/ClientSession/UnsafeContext.cs
cs/src/core/Index/FASTER/FASTERImpl.cs

ConcurrentWriter and InPlaceUpdater check for Tombstone, but the caller didn't after those returned. Note that we need to retain the initial Tombstone check (before CW and IPU) so we don't return RETRY_NOW for it.

[C#] Handle race condition where Tombstone can be set after it is checked

---

cs/src/core/Index/FASTER/FASTERImpl.cs

Wait index checkpoint phase should behave similarly to wait flush - perform create-new-record during a checkpoint if record is not in the new version (during the snapshot).

[C#] Wait index checkpoint phase should behave similarly to wait flush

---

cs/src/core/Index/FASTER/FASTERImpl.cs
cs/test/AdvancedLockTests.cs
cs/test/ReadCacheChainTests.cs

Delete doesn't need to do anything if record is already deleted
Add Unseal() on InternalContinuePendingRMW (as InternalContinuePendingRead does)
Add UTs to verify Recover() clears locks
Add an Assert in MultiThreadTests to perhaps provide info on intermittent "output.Memory" null ref

[C#]Fix missing Tombstone check in ReadOnly for RMW/Upsert

---

cs/src/core/ClientSession/BasicContext.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/ClientSession/LockableContext.cs
cs/src/core/ClientSession/LockableUnsafeContext.cs
cs/src/core/FasterLog/FasterLogIterator.cs
cs/test/LockableUnsafeContextTests.cs
cs/test/ReadCacheChainTests.cs

Expose Acquire/Release for LC
FasterLogIterator dispose fix
BasicContext and LockableContext are "stateless" struct wrappers for client session

[C#] Do not auto-acquire lockable context

---

cs/samples/FasterLogSample/Program.cs
cs/src/core/ClientSession/BasicContext.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/ClientSession/IUnsafeContext.cs
cs/src/core/ClientSession/LockableContext.cs
cs/src/core/ClientSession/LockableUnsafeContext.cs
cs/src/core/ClientSession/UnsafeContext.cs
cs/src/core/Epochs/LightEpoch.cs
cs/test/LockableUnsafeContextTests.cs
cs/test/ModifiedBitTests.cs
docs/_docs/30-fasterkv-manual-locking.md

Also, remove overload of session Resume that returns epoch (no longer needed after native locking support added).

[C#] Use long type for epochs

---

cs/src/core/Allocator/LockEvictionObserver.cs
cs/test/LockableUnsafeContextTests.cs

The iter.GetNext(out RecordInfo, out Key, out Value) form does not work for VarLen so this was replaced with the (out RecordInfo) overload and calling iter.GetKey(), which works for all types.

[C#]Fix GetNext call in LockEvictionObserver

---

cs/src/core/Epochs/LightEpoch.cs

In a class that has `static ctor`, accessing static fields include `ThreadStatic` is challenging. We have a helper call to find the base address of the variable to access and generally this helper call is not optimizable. Meaning, if we are accessing such variable in a loop, the corresponding helper call cannot be move around to optimize code. The reason being, we need to be precise at what time the ctor will be called and there are rules that govern that. Because of lack of ability to move the helper call around, if we access a static variable inside a loop, we will be calling the helper call in every single iteration. Find the base address is time consuming as well because it has to go through at least 3 looks up tables (module, thread and the variable). 
However, in absence of `static …

Optimize the uses of ThreadStatic in class having static ctor

---

cs/benchmark/FasterSpanByteYcsbBenchmark.cs
cs/benchmark/FasterYcsbBenchmark.cs
cs/src/core/ClientSession/BasicContext.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/ClientSession/ILockableContext.cs
cs/src/core/ClientSession/IUnsafeContext.cs
cs/src/core/ClientSession/LockableContext.cs
cs/src/core/ClientSession/LockableUnsafeContext.cs
cs/src/core/ClientSession/UnsafeContext.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/stress/SessionWrapper.cs
cs/stress/TestLoader.cs
cs/test/AdvancedLockTests.cs
cs/test/DisposeTests.cs
cs/test/LockableUnsafeContextTests.cs
cs/test/ModifiedBitTests.cs
cs/test/ReadCacheChainTests.cs
cs/test/StateMachineTests.cs
cs/test/ThreadSession.cs
cs/test/UnsafeContextTests.cs

Also, this changes "Acquire/Release" to BeginUnsafe/EndUnsafe (for manual epoch management) and Begin/EndLockable (for manual locking).
Added a check to BeginLockable to wait until any in-prepare checkpoint state has moved on.

[C#] Convert *UnsafeContext to structs and acquire on demand

---

cs/src/core/FasterLog/FasterLog.cs
cs/src/core/FasterLog/FasterLogIterator.cs
cs/test/FasterLogScanTests.cs

If scan is below begin address, update nextAddress before returning. Also, make sure currentAddress and outNextAddress are consistent w.r.t. shared nextAddress field.

[C#] FasterLog scan fix when begin address moves ahead of scan

---

cs/src/core/Index/CheckpointManagement/DeviceLogCommitCheckpointManager.cs
cs/src/core/Index/Recovery/IndexRecovery.cs
cs/src/core/Index/Recovery/Recovery.cs

This PR contains the below changes
- public access to CheckpointManager to allow users to retrieve Guid tokens and access corresponding files.
- methods to retrieve latest checkpoint hybrid log and index Guid tokens.
- methods to retrieve file sizes for corresponding Guid tokens
- protected access to deviceFactory and checkpointNamingScheme for users to able to extend the -DeviceLogCommitCheckpointManager class

Checkpoint Retrieval and Management from User Space

---

cs/src/core/Device/LocalStorageDevice.cs
cs/src/core/Device/ManagedLocalStorageDevice.cs

Fixes #767 
Avoids `Int32.Parse` failure on platforms that return the main log file as one of the matches for `di.GetFiles(bareName + "*")`.

Fix: Some platforms try get a segmentId from the main log file.

---

cs/src/core/Index/Common/FasterKVSettings.cs
cs/src/core/Index/FASTER/Implementation/ContainsKeyInMemory.cs
cs/src/core/Index/FASTER/Implementation/ContinuePending.cs
cs/src/core/Index/FASTER/Implementation/ModifiedBitOperation.cs
cs/src/core/Index/FASTER/Implementation/ReadCache.cs

Fix https://github.com/microsoft/FASTER/issues/780

Fix calls to TraceBack to use returned addresses correctly

---

cs/remote/src/FASTER.server/Servers/FasterServerBase.cs
cs/src/core/Device/StorageDeviceBase.cs
cs/src/core/Index/FASTER/Implementation/InternalRMW.cs
cs/src/core/Index/FASTER/Implementation/InternalUpsert.cs

Fix https://github.com/microsoft/FASTER/issues/784

Minor issues in session mgmt, truncate, etc

---

cs/src/core/FasterLog/FasterLog.cs

Else it doesn't respond if the first call after recovery is a get call
As the value of persisted commit number remained 0. So was unable to send back the response.

Set persisted commit number after recovery

---

cs/src/core/Index/Common/RecordInfo.cs
cs/src/core/Index/FASTER/FASTERBase.cs
cs/src/core/Index/FASTER/FASTERIterator.cs
cs/src/core/Index/FASTER/Implementation/HashEntryInfo.cs
cs/src/core/Index/FASTER/Implementation/Helpers.cs
cs/src/core/Index/FASTER/Implementation/InternalDelete.cs
cs/src/core/Index/FASTER/Implementation/InternalRMW.cs
cs/src/core/Index/FASTER/Implementation/InternalRead.cs
cs/src/core/Index/FASTER/Implementation/InternalUpsert.cs
cs/src/core/Index/Recovery/Recovery.cs
cs/test/ComponentRecoveryTests.cs
cs/test/TestUtils.cs

Fix HashBucket latching:
- Add HEI.firstBucket and make sure the latching uses this
- Improve the latching logic to check appropriate conditions and spin to retry (with max spin count to failure)
- Fix FindTagOrFreeInternal to retry if CAS fails, and remove the unneeded recordExists variable
- Remove some unused methods

[C#] Fix HashBucket latching

---

cs/samples/ReadAddress/VersionedReadApp.cs

ReadAddress sample missing `ReadOptions.StartAddress` assignment in `ScanStore` method.

Bug fix for ReadAddress sample

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/BlittableAllocator.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Allocator/VarLenBlittableAllocator.cs
cs/src/core/ClientSession/ClientSession.cs
cs/src/core/FasterLog/FasterLog.cs
cs/src/core/Index/CheckpointManagement/DeviceLogCommitCheckpointManager.cs
cs/src/core/Index/Common/CheckpointSettings.cs
cs/src/core/Index/Common/FasterKVSettings.cs
cs/src/core/Index/FASTER/FASTER.cs
cs/src/core/Index/FASTER/FASTERThread.cs
cs/src/core/Index/Recovery/Checkpoint.cs
cs/src/core/Index/Recovery/ICheckpointManager.cs
cs/src/core/Index/Recovery/Recovery.cs
cs/src/core/Index/Synchronization/HybridLogCheckpointTask.cs
cs/src/core/Index/Synchronization/IndexResizeStateMachine.cs
cs/src/core/Index/Synchronization/VersionChangeStateMachine.cs
cs/test/FasterLogTests.cs
cs/test/RecoveryChecks.cs

Add Checkpoint option (default disabled) for whether we use a barrier to ensure that threads are not in two different checkpoint versions at the same time.
In the (PREPARE, v) phase, refresh will wait for all threads to get to the next version (IN_PROGRESS, v+1) before proceeding with the operation.
Also support basic recovery rollback, just call Recover on an existing store, and it will undo any uncheckpointed data before recovering to the given checkpoint. Make sure store is quiesced before attempting to call Recover on it.

[C#] Option to create barrier at checkpoint version switch, support rollback

---

cs/src/core/Epochs/EpochProtectedVersionScheme.cs

Use correct compare-and-swapped value to guard against rare race when conflicting state machine has been removed

[C#] EPVS Quick Fix

---

cs/src/core/Allocator/AllocatorBase.cs
cs/src/core/Allocator/BlittableAllocator.cs
cs/src/core/Allocator/BlittableScanIterator.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Allocator/GenericScanIterator.cs
cs/src/core/Allocator/IScanIteratorFunctions.cs
cs/src/core/Allocator/MemoryPageScanIterator.cs
cs/src/core/Allocator/VarLenBlittableAllocator.cs
cs/src/core/Allocator/VarLenBlittableScanIterator.cs
cs/src/core/Compaction/FASTERCompaction.cs
cs/src/core/Index/Common/RecordMetadata.cs
cs/src/core/Index/FASTER/FASTERIterator.cs
cs/src/core/Index/FASTER/Implementation/RecordSource.cs
cs/src/core/Index/FASTER/LogAccessor.cs
cs/test/BlittableIterationTests.cs
cs/test/GenericIterationTests.cs
cs/test/VarLenBlittableIterationTests.cs

Remove erroneous 'ref' in assignment to VarLenBlittableScanIterator.GetNext's "out RecordInfo"
Add a default implementation to some IScanIteratorFunctions members
Make RecordMetadata a readonly struct
Fix https://github.com/microsoft/FASTER/issues/829

[C#] Fix VarLenBlittableScanIterator.GetNext RecordInfo output

---

cs/FASTER.sln
cs/playground/MemoryDb/MemoryDb.csproj
cs/playground/MemoryDb/Program.cs
cs/src/core/VarLen/MemoryVarLenStruct.cs
cs/src/core/VarLen/ReadOnlyMemoryVarLenStruct.cs
cs/test/SingleWriterTests.cs

Fix https://github.com/microsoft/FASTER/issues/832
Note: we still cannot use Memory<byte> and ReadOnlyMemory<byte> with read cache turned on. Use SpanByte instead.

Increase refCache size for Memory based API

---

cs/src/core/Index/Common/RecordInfo.cs
cs/src/core/Index/FASTER/Implementation/ConditionalCopyToTail.cs
cs/src/core/Index/FASTER/Implementation/Helpers.cs
cs/src/core/Index/FASTER/Implementation/InternalRMW.cs
cs/src/core/Index/FASTER/Implementation/InternalRead.cs
cs/src/core/Index/FASTER/Implementation/InternalUpsert.cs
cs/src/core/Index/FASTER/Implementation/TryCopyToReadCache.cs
cs/src/core/Index/FASTER/Implementation/TryCopyToTail.cs
cs/test/MiscFASTERTests.cs
cs/test/StateMachineTests.cs

- Set both Sealed and Invalid on new records to ensure consistency both during normal operations and after recovery, which clears the Sealed bit.
- Seal ConcurrentUpdater and InPlaceUpdater source records on successful RCU even when not doing Standard locking

[C#] Record Sealing consistency

---

cs/src/core/Allocator/BlittableScanIterator.cs
cs/src/core/Allocator/GenericScanIterator.cs
cs/src/core/Allocator/VarLenBlittableScanIterator.cs
cs/src/core/Index/FASTER/FASTERBase.cs
cs/src/core/Index/FASTER/Implementation/HashEntryInfo.cs
cs/src/core/Index/FASTER/Implementation/InternalDelete.cs
cs/src/core/Index/FASTER/Implementation/ReadCache.cs
cs/src/core/Index/FASTER/Implementation/RecordSource.cs
cs/src/core/Index/Recovery/Recovery.cs
cs/test/BlittableLogScanTests.cs
cs/test/GenericLogScanTests.cs
cs/test/RecoverContinueTests.cs
cs/test/SpanByteLogScanTests.cs

- Fix InternalDelete elision from HashBucketEntry (set entire word to 0)
- Fix iterators to jump ahead to BeginAddress if they're below it, rather than throw
- Remove unused HashBucketEntry.Pending
- Remove unnecessary ReadCacheEvictChain call in DetachAndReattachReadCacheChain

[C#] Fix Delete record elision

---

cs/src/core/Epochs/EpochProtectedVersionScheme.cs
cs/src/core/Epochs/LightEpoch.cs
cs/src/core/FasterLog/FasterLog.cs
cs/src/core/Index/FASTER/FASTERBase.cs
cs/src/core/Index/Synchronization/IndexResizeStateMachine.cs

- Ensure threads calling BumpCurrentEpoch are protected
- Back out change for shared bucket lock to wait for writer

[C#] BumpCurrentEpoch calling threads must be protected

---

cs/src/core/Index/Common/Contexts.cs

Based on our conversation and the changes in #838 it appears to me that it is relatively easy to remain compatible with the v4 checkpoint version by using the same value for `snapshotStartFlushedLogicalAddress` and `flushedLogicalAddress`.
If that is indeed the case, this PR should make it possible to load older checkpoints, thus not breaking storage compatibility.

allow reading v4 checkpoints for compatibility

---

cs/src/core/Epochs/LightEpoch.cs
cs/src/core/FasterLog/FasterLog.cs

Revise BumpEpoch to accommodate calling from both protected and unprotected contexts. Revise FasterLog completion logic to avoid epoch double-protect. From now on, users should assume that any trigger action associated with BumpEpoch will execute on a protected thread after it is safe. Caller thread of BumpEpoch can be either protected or unprotected.
fix #872

[C#] Clarify and enforce BumpEpoch protection assumptions

---

cs/src/core/FASTER.core.csproj
cs/src/core/FASTER.core.nuspec

When using the net6.0 target of FASTER with Netherite on a Durable Functions host, it is not possible to load version 7.0.0 of Microsoft.Extensions.Logging.
 
To fix this we can add a condition in the project file which uses the 6.0.0 version when building the net6.0 target. 
For reference: we had this same problem for earlier versions and targets (see #717) and are adopting the same solution.

Use Azure-Functions-compatible Microsoft.Extensions.Logging

---

cs/src/core/Allocator/BlittableAllocator.cs
cs/src/core/Allocator/GenericAllocator.cs
cs/src/core/Allocator/GenericFrame.cs
cs/src/core/Utilities/Utility.cs
cs/src/core/VarLen/FixedLengthStruct.cs
cs/stress/TestLoader.cs

This ports the changes done by @PaulusParssinen in https://github.com/microsoft/garnet/pull/39 to FASTER
The changes are a bit simpler as in Garnet as many of those fields are not internal, so I skipped the property conversion.

Port the Unsafe.SizeOf Fixes from garnet

---

cs/src/core/Utilities/Utility.cs

This ports the change done by @paulusparssinen done in https://github.com/microsoft/garnet/pull/36 to FASTER.
This only applies to the builds for .NET STANDARD 2.1 and 6_0+ as otherwise the helper method is not available, the reflection method is also still used in the code.

use IsReferenceOrContainsReferences for .NET Standard 2.1+ and 6_0+

---

cs/src/core/FasterLog/FasterLogIterator.cs

Fix commit record pointer calculation by including headerSize value in the base offset. 
Relates to #691

Fix commit record pointer offset calculation

---

cs/src/core/Index/Common/Contexts.cs
cs/src/core/Index/FASTER/Implementation/ContinuePending.cs
cs/src/core/Index/FASTER/Implementation/InternalRead.cs
cs/test/CompletePendingTests.cs

Fix ContinuePendingRead to account for new records for the same key that were added and then went to disk during the pending Read operation.

Fix ContinuePendingRead to account for new records

---

cs/remote/samples/FixedLenServer/FixedLenServer.csproj
cs/remote/samples/VarLenServer/VarLenServer.csproj

Updated Microsoft.Extensions.* nuget packages to "Latest Stable" build in FixedLenServer sample and VarLenServer sample as they were out of compliance for security (dependency on System.Text.Json)

Updated Microsoft.Extensions.* nuget packages for security compliance
